# Pipeline to release new containers on container apps

trigger: none
pr: none
resources:
  repositories:
    - repository: templates
      type: git
      ref: main
      name: Infrastructure/core-templates

parameters:
  - name: imageOverwrite
    displayName: Image that will be deployed

variables:
  # Variable called 'image_manual_override' is defined for optional per-run manual override.
  - group: Secrets
  - group: Non-secrets
    
pool: linux-k8s

stages:
  - template: .pipelines/deploy-game-logic-dev.yml
    parameters:
      helmRepoPassword: $(HELM-REPO-PASSWORD)
      dockerImage: ${{ parameters.imageOverwrite }}


  - template: .pipelines/deploy-game-logic-testnet.yml
    parameters:
      helmRepoPassword: $(HELM-REPO-PASSWORD)
      dockerImage: ${{ parameters.imageOverwrite }}


  - template: .pipelines/deploy-game-logic-staging.yml
    parameters:
      helmRepoPassword: $(HELM-REPO-PASSWORD)
      dockerImage: ${{ parameters.imageOverwrite }}

  - template: .pipelines/deploy-game-logic-prod.yml
    parameters:
      helmRepoPassword: $(HELM-REPO-PASSWORD)
      dockerImage: ${{ parameters.imageOverwrite }}



# autoscaling percentage values are bsed on request values, not limits.
# by default, we request 100 millicores. 190% of 100 millicores is 190 millicores.
