# Android build and release pipeline
# This pipeline is respsonsible for building the Android APK, and uploading to Azure Storage.

name: $(Rev:r)

trigger: none
pr: none

resources:
  repositories:
  - repository: self
  - repository: templates
    type: git
    ref: main
    name: Infrastructure/core-templates
    
variables:
- group: Secrets
- group: Non-secrets
- name: unity_password
  value: $(UNITY-PASSWORD)
- name: unity_serial
  value: $(UNITY-SERIAL)

pool: macos

stages:
- stage: AndroidBuild
  displayName: Android Build
  jobs:
    - job: AndroidBuild
      displayName: Android Build
      steps:
      - checkout: self
        lfs: true
        submodules: true
      - template: pipelines/unity-build.yml@templates
        parameters:
          configuration: Release
          unity_username: ian.moroney@firstlight.games
          unity_password: $(unity_password)
          unity_serial: $(unity_serial)
          workingDirectory: .
