# Android build and release pipeline
# This pipeline is respsonsible for building the Android APK, and uploading to Azure Storage.

name: $(Rev:r)

trigger: none
pr: none

resources:
  repositories:
  - repository: self
  - repository: templates
    type: git
    ref: main
    name: Infrastructure/core-templates

parameters:
  - name: build_type
    displayName: Select Build Type
    type: string
    default: DEVELOPMENT_BUILD
    values:
      - DEVELOPMENT_BUILD
      - RELEASE_BUILD
      - STORE_BUILD
  - name: server_environment
    displayName: Select Target Server Environment
    type: string
    default: DEVELOPMENT_SERVER
    values:
      - DEVELOPMENT_SERVER
      - STAGE_SERVER
      - LIVE_SERVER
  - name: runUnitTests
    displayName: Run Unit Tests?
    type: string
    default: false
    values:
      - false
      - true

variables:
- group: Secrets
- group: Non-secrets
- name: unity_password
  value: $(UNITY-PASSWORD)
- name: unity_serial
  value: $(UNITY-SERIAL)
- name: branchName
  value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
- ${{  if eq(parameters['build_type'], 'DEVELOPMENT_BUILD') }}:
    - name: configuration
      value: "Debug"
    - name: androidFileType
      value: "apk"
- ${{  if eq(parameters['build_type'], 'RELEASE_BUILD') }}:
    - name: configuration
      value: "Release"
    - name: androidFileType
      value: "apk"
- ${{  if eq(parameters['build_type'], 'STORE_BUILD') }}:
    - name: configuration
      value: "Release"
    - name: androidFileType
      value: "aab"
- name: build_type
  value: ${{ parameters.build_type }}
- name: server_environment
  value: ${{ parameters.server_environment }}
- name: webhookUrl
  value: $(SLACK-WEBHOOK-URL)
- name: cuttlyApiKey
  value: $(PROD-COMMON-CUTTLY-KEY)

pool: macos

stages:
- stage: AutoBuilds
  displayName: Auto Builds
  jobs:
    - job: EditorTests
      displayName: Run Editor Test Suite
      condition: eq('${{ parameters.runUnitTests }}', true)
      steps:
      - checkout: self
        lfs: true
        submodules: true
      - template: pipelines/unity-tests.yml@templates
        parameters:
          testPlatform: EditMode
    - job: AndroidBuild
      timeoutInMinutes: 0
      dependsOn: EditorTests
      displayName: Android Build
      condition: in(dependencies.EditorTests.result, 'Succeeded', 'Skipped')
      steps:
      - checkout: self
        lfs: true
        submodules: true
      - template: pipelines/unity-build.yml@templates
        parameters:
          configuration: ${{ variables.configuration }}
          platform: Android
          unity_username: ian.moroney@firstlight.games
          unity_password: $(unity_password)
          unity_serial: $(unity_serial)
          workingDirectory: .
          branchName: $(branchName)
          build_type: ${{ variables.build_type }}
          server_environment: ${{ variables.server_environment }}
          webhookUrl: $(webhookUrl)
          cuttlyApiKey: $(cuttlyApiKey)
          androidFileType: $(androidFileType)
    - job: iOSBuild
      timeoutInMinutes: 0
      dependsOn: EditorTests
      displayName: iOS Build
      condition: in(dependencies.EditorTests.result, 'Succeeded', 'Skipped')
      steps:
      - checkout: self
        lfs: true
        submodules: true
      - template: pipelines/unity-build.yml@templates
        parameters:
          configuration: ${{ variables.configuration }}
          platform: iOS
          unity_username: ian.moroney@firstlight.games
          unity_password: $(unity_password)
          unity_serial: $(unity_serial)
          certPwd: $(certPwd)
          workingDirectory: .
          branchName: $(branchName)
          build_type: ${{ parameters.build_type }}
          server_environment: ${{ parameters.server_environment }}
          webhookUrl: $(webhookUrl)
          cuttlyApiKey: $(cuttlyApiKey)
          developmentiOSCertPwd: $(developmentiOSCertPwd)
          distributioniOSCertPwd: $(distributioniOSCertPwd)
