# Game Logic server container build and release pipeline
# This pipeline is respsonsible for building the game logic code and pushing it to the container registry

name: $(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - 'develop'
  paths:
    include:
    - Backend
    - pipeline-game-logic-server-ci.yml
pr: none

resources:
  repositories:
  - repository: self
  - repository: templates
    type: git
    ref: main
    name: Infrastructure/core-templates
    
variables:
- group: Non-secrets
- name: serviceConnection
  value: AzureRM
- name: dockerfile
  value: GameLogicService/Dockerfile
- name: vmImageName
  value: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  displayName: Build and push image
  jobs:
    - job: BuildPush
      displayName: Build and push
      steps:
      - checkout: self
        lfs: true
        submodules: true
      - template: pipelines/docker-build-push.yml@templates
        parameters:
          serviceConnection: $(serviceConnection)
          containerRegistry: firstlight
          repository: game-logic-service
          workingDirectory: Backend
          buildArgs: |
            -f $(dockerfile) . --no-cache
