# Android build and release pipeline
# This pipeline is respsonsible for building the Android APK, and uploading to Azure Storage.

name: $(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - 'develop'
    - 'release/*'
    - 'master'
pr: none

resources:
  repositories:
  - repository: self
  - repository: templates
    type: git
    ref: main
    name: Infrastructure/core-templates

variables:
- group: Secrets
- group: Non-secrets
- name: unity_password
  value: $(UNITY-PASSWORD)
- name: unity_serial
  value: $(UNITY-SERIAL)
- name: branchName
  value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
- name: configuration
  ${{  if eq(variables['Build.SourceBranch'], 'refs/heads/develop')  }}:
    value: "Debug"
  ${{  if or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))  }}:
    value: "Release"
- name: build_type
  ${{  if eq(variables['Build.SourceBranch'], 'refs/heads/develop')  }}:
    value: "DEVELOPMENT_BUILD"
  ${{  if startsWith(variables['Build.SourceBranch'], 'refs/heads/release')  }}:
    value: "RELEASE_BUILD"
  ${{  if eq(variables['Build.SourceBranch'], 'refs/heads/master')  }}:
    value: "STORE_BUILD"
- name: server_environment
  ${{  if eq(variables['Build.SourceBranch'], 'refs/heads/develop')  }}:
    value: "DEVELOPMENT_SERVER"
  ${{  if startsWith(variables['Build.SourceBranch'], 'refs/heads/release')  }}:
    value: "STAGE_SERVER"
  ${{  if eq(variables['Build.SourceBranch'], 'refs/heads/master')  }}:
    value: "LIVE_SERVER"
- name: webhookUrl
  value: $(SLACK-WEBHOOK-URL)
- name: cuttlyApiKey
  value: (PROD-COMMON-CUTTLY-KEY)

pool: macos

stages:
- stage: AutoBuilds
  displayName: Auto Builds
  jobs:
    - job: EditorTests
      displayName: Run Editor Test Suite
      condition: eq('${{ variables.runUnitTests }}', true)
      steps:
      - checkout: self
        lfs: true
        submodules: true
      - template: pipelines/unity-tests.yml@templates
        parameters:
          testPlatform: EditMode
    - job: AndroidBuild
      timeoutInMinutes: 0
      dependsOn: EditorTests
      displayName: Android Build
      condition: in(dependencies.EditorTests.result, 'Succeeded', 'Skipped')
      steps:
      - checkout: self
        lfs: true
        submodules: true
      - template: pipelines/unity-build.yml@templates
        parameters:
          configuration: $(configuration)
          platform: Android
          unity_username: ian.moroney@firstlight.games
          unity_password: $(unity_password)
          unity_serial: $(unity_serial)
          workingDirectory: .
          branchName: $(branchName)
          build_type: ${{ variables.build_type }}
          server_environment: ${{ variables.server_environment }}
          webhookUrl: $(webhookUrl)
          cuttlyApiKey: $(cuttlyApiKey)
    - job: iOSBuild
      timeoutInMinutes: 0
      dependsOn: EditorTests
      displayName: iOS Build
      condition: in(dependencies.EditorTests.result, 'Succeeded', 'Skipped')
      steps:
      - checkout: self
        lfs: true
        submodules: true
      - template: pipelines/unity-build.yml@templates
        parameters:
          configuration: $(configuration)
          platform: iOS
          unity_username: ian.moroney@firstlight.games
          unity_password: $(unity_password)
          unity_serial: $(unity_serial)
          certPwd: $(certPwd)
          workingDirectory: .
          branchName: $(branchName)
          build_type: ${{ variables.build_type }}
          server_environment: ${{ variables.server_environment }}
          webhookUrl: $(webhookUrl)
          cuttlyApiKey: $(cuttlyApiKey)
