//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Design/InputSystem/LocalInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace FirstLight.Game.Input
{
    public partial class @LocalInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @LocalInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""LocalInput"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""0a495ce5-d6d1-466f-8ffe-01913fa7cfad"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""80e0617a-f7d5-4342-9ec4-8445552b4b71"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone(min=0.12,max=0.92)"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6600ce1c-2814-459a-816a-acbe147764c8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone(min=0.2,max=0.9)"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special Aim"",
                    ""type"": ""PassThrough"",
                    ""id"": ""15d88791-423a-4e9d-b67e-a41cf186bf27"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim Button"",
                    ""type"": ""Button"",
                    ""id"": ""cb1a0282-e279-4d29-9642-33897f62e175"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special Button0"",
                    ""type"": ""Button"",
                    ""id"": ""21ef680b-1285-493a-9407-c14b86f56123"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special Button1"",
                    ""type"": ""Button"",
                    ""id"": ""2cbc1f2b-41d0-4084-a20d-1b13d6d48087"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b565c55a-4974-408e-b73b-e226a7524ca4"",
                    ""path"": ""<OnscreenControlsDevice>/LeftJoystickDirection"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""044e9e5c-f961-4da4-9dd9-0b341cf281a7"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""e1fbe242-31fe-4a58-abd8-b66998943edc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fe527f3d-28c5-44b4-be6e-b28aa4e6e891"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e6448fda-3179-4268-8f66-91d7aa84d321"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2012b0b0-6b66-4755-b9ad-fde7439b9538"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e4f00fc2-51ba-49b0-b3d9-0c29213ecb1b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1cfbb9e0-d5e8-4e7d-9ff0-58ac05f0dab6"",
                    ""path"": ""<OnscreenControlsDevice>/Special0PointerDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Button0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14fa2f90-c497-46d8-af86-befae1fe0be8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Button0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5e28871-0470-4c5f-af5a-4a2b7f0ee275"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Button0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68a4f95b-1418-4f70-9873-c2caa7f8eb3a"",
                    ""path"": ""<OnscreenControlsDevice>/RightJoystickDirection"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a92ec02-6e87-4b7f-a082-7a12a41fa008"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8b7be71-eaa6-4a6b-9426-c922c5813756"",
                    ""path"": ""<OnscreenControlsDevice>/Special1PointerDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Button1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab55e23e-32ab-4eed-a23d-896b02a2681a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Button1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4aea5f6-b9bf-4e7e-a6e6-035a6801c80f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Button1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""242328ef-5041-4d0f-ae62-c52189890edd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""725d7c60-9da5-44d6-8bfe-56f5579fa51b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b07eacd3-9838-42f3-aa65-b0243a075f0f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a8bed29e-aac9-4573-9a5b-df8469a55aeb"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ecd9890e-46ea-4db6-bdb4-3c7da0878c9e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6338f639-c9b8-4e94-881e-74c54b904a8b"",
                    ""path"": ""<OnscreenControlsDevice>/RightJoystickPointerDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54b8e9e7-46d2-4245-9fee-14901b3a6f4b"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab87f8be-0780-4589-a75d-1af9d11fa73e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9251bfc5-1857-4845-a950-4a2a94e75658"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b75ed8b-ead6-4845-9789-408125a8445c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35883955-d13d-4e0c-aa63-7ca7b43fefa2"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa4a40b8-8c2b-413b-bdc4-1b12054e5d04"",
                    ""path"": ""<OnscreenControlsDevice>/SpecialAimDirection"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff0cb73a-335d-48bd-8b13-aefe7905327e"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Direction Keys"",
                    ""id"": ""492cb57b-1ab1-4d9a-831b-a32505cfe4bc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Aim"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""205c0646-f15e-46db-9e72-1ef5a8035616"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bde0d329-73ef-4d5a-bf9d-a1b001c60282"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7e1f8c0f-ec94-48d1-ae59-52eae93019c6"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""976ce886-22a8-4da3-bf3d-5dcf2e54cb38"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Gameplay
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
            m_Gameplay_Aim = m_Gameplay.FindAction("Aim", throwIfNotFound: true);
            m_Gameplay_SpecialAim = m_Gameplay.FindAction("Special Aim", throwIfNotFound: true);
            m_Gameplay_AimButton = m_Gameplay.FindAction("Aim Button", throwIfNotFound: true);
            m_Gameplay_SpecialButton0 = m_Gameplay.FindAction("Special Button0", throwIfNotFound: true);
            m_Gameplay_SpecialButton1 = m_Gameplay.FindAction("Special Button1", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay
        private readonly InputActionMap m_Gameplay;
        private IGameplayActions m_GameplayActionsCallbackInterface;
        private readonly InputAction m_Gameplay_Move;
        private readonly InputAction m_Gameplay_Aim;
        private readonly InputAction m_Gameplay_SpecialAim;
        private readonly InputAction m_Gameplay_AimButton;
        private readonly InputAction m_Gameplay_SpecialButton0;
        private readonly InputAction m_Gameplay_SpecialButton1;
        public struct GameplayActions
        {
            private @LocalInput m_Wrapper;
            public GameplayActions(@LocalInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Gameplay_Move;
            public InputAction @Aim => m_Wrapper.m_Gameplay_Aim;
            public InputAction @SpecialAim => m_Wrapper.m_Gameplay_SpecialAim;
            public InputAction @AimButton => m_Wrapper.m_Gameplay_AimButton;
            public InputAction @SpecialButton0 => m_Wrapper.m_Gameplay_SpecialButton0;
            public InputAction @SpecialButton1 => m_Wrapper.m_Gameplay_SpecialButton1;
            public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
            public void SetCallbacks(IGameplayActions instance)
            {
                if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                    @Aim.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAim;
                    @Aim.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAim;
                    @Aim.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAim;
                    @SpecialAim.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecialAim;
                    @SpecialAim.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecialAim;
                    @SpecialAim.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecialAim;
                    @AimButton.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAimButton;
                    @AimButton.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAimButton;
                    @AimButton.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAimButton;
                    @SpecialButton0.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecialButton0;
                    @SpecialButton0.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecialButton0;
                    @SpecialButton0.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecialButton0;
                    @SpecialButton1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecialButton1;
                    @SpecialButton1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecialButton1;
                    @SpecialButton1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecialButton1;
                }
                m_Wrapper.m_GameplayActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Aim.started += instance.OnAim;
                    @Aim.performed += instance.OnAim;
                    @Aim.canceled += instance.OnAim;
                    @SpecialAim.started += instance.OnSpecialAim;
                    @SpecialAim.performed += instance.OnSpecialAim;
                    @SpecialAim.canceled += instance.OnSpecialAim;
                    @AimButton.started += instance.OnAimButton;
                    @AimButton.performed += instance.OnAimButton;
                    @AimButton.canceled += instance.OnAimButton;
                    @SpecialButton0.started += instance.OnSpecialButton0;
                    @SpecialButton0.performed += instance.OnSpecialButton0;
                    @SpecialButton0.canceled += instance.OnSpecialButton0;
                    @SpecialButton1.started += instance.OnSpecialButton1;
                    @SpecialButton1.performed += instance.OnSpecialButton1;
                    @SpecialButton1.canceled += instance.OnSpecialButton1;
                }
            }
        }
        public GameplayActions @Gameplay => new GameplayActions(this);
        public interface IGameplayActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnAim(InputAction.CallbackContext context);
            void OnSpecialAim(InputAction.CallbackContext context);
            void OnAimButton(InputAction.CallbackContext context);
            void OnSpecialButton0(InputAction.CallbackContext context);
            void OnSpecialButton1(InputAction.CallbackContext context);
        }
    }
}
