/* AUTO GENERATED CODE */

using System.Collections.Generic;
using System.Collections.ObjectModel;
using FirstLight.AddressablesExtensions;

// ReSharper disable InconsistentNaming
// ReSharper disable once CheckNamespace

namespace FirstLight.Game.Ids
{
	public enum AddressableId
	{
		Timeline_FtueTimeline,
		Collections_WeaponSkins_Config,
		Collections_CharacterSkins_Config,
		Maps_MapAssetConfigs,
		Maps_QuantumMapConfigs,
		Configs_AdjectiveDataConfigs,
		Configs_AdventureAssetConfigs,
		Configs_AudioMainMenuAssetConfigs,
		Configs_AudioMatchAssetConfigs,
		Configs_AudioMixerConfigs,
		Configs_AudioSharedAssetConfigs,
		Configs_AudioWeaponConfigs,
		Configs_BaseEquipmentStatConfigs,
		Configs_BattlePassConfigs,
		Configs_BotConfigs,
		Configs_BotDifficultyConfigs,
		Configs_ChestConfigs,
		Configs_ConsumableConfigs,
		Configs_CustomAssetConfigs,
		Configs_DestructibleConfigs,
		Configs_DummyAssetConfigs,
		Configs_EditionDataConfigs,
		Configs_EquipmentMaterialStatConfigs,
		Configs_EquipmentRarityAssetConfigs,
		Configs_EquipmentRewardConfigs,
		Configs_EquipmentStatConfigs,
		Configs_FactionDataConfigs,
		Configs_FuseConfigs,
		Configs_GameConfigs,
		Configs_GameModeConfigs,
		Configs_GameModeRotationConfigs,
		Configs_GradeDataConfigs,
		Configs_GraphicsConfig,
		Configs_IndicatorVfxAssetConfigs,
		Configs_LiveopsFeatureFlagConfigs,
		Configs_LiveopsSegmentActionConfigs,
		Configs_MainMenuAssetConfigs,
		Configs_MainMenuCharacterAnimationConfigs,
		Configs_ManufacturerDataConfigs,
		Configs_MapGridConfigs,
		Configs_MatchRewardConfigs,
		Configs_MatchmakingAndRoomConfigs,
		Configs_MaterialDataConfigs,
		Configs_MaterialVfxConfigs,
		Configs_MutatorConfigs,
		Configs_PlayerLevelConfigs,
		Configs_PlayerRankAssetConfigs,
		Configs_QuantumPrototypeAssetConfigs,
		Configs_RarityDataConfigs,
		Configs_RepairDataConfigs,
		Configs_ResourcePoolConfigs,
		Configs_SceneAssetConfigs,
		Configs_ScrapConfigs,
		Configs_ShrinkingCircleConfigs,
		Configs_SpecialConfigs,
		Configs_SpecialMoveAssetConfigs,
		Configs_SpriteAssetConfigs,
		Configs_StatConfigs,
		Configs_TrophyRewardConfigs,
		Configs_TutorialBattlePassConfigs,
		Configs_TutorialRewardConfigs,
		Configs_UpgradeDataConfigs,
		Configs_VfxConfigs,
		Configs_VideoAssetConfigs,
		Configs_WeaponConfigs,
		Configs_Settings_AssetResources,
		Configs_Settings_Deterministic_Config,
		Configs_Settings_PhotonServerSettings,
		Configs_Settings_QuantumRunnerConfigs,
		Configs_Settings_SimulationConfig,
		Configs_Settings_UiConfigs,
		Collections_ProfilePicture_AvatarCollectableConfigs,
		Maps_FtueDeck_FtueDeck,
		Maps_FtueDeck_FtueDeckScene,
		Maps_FtueDeck_FtueDeck_LM0_final,
		Maps_FtueDeck_FtueDeck_LMA1_final,
		Maps_FtueDeck_FtueDeck_LMA2_final,
		Maps_FtueDeck_FtueDeck_LMA3_final,
		Maps_FtueDeck_FtueDeck_NavMesh,
		Maps_FtueDeck_FtueDeck_NavMesh_data,
		Maps_FtueDeck_FtueDeck_mesh,
		Maps_FtueDeck_LightingData,
		Maps_FtueDeck_NavMesh,
		Maps_FtueDeck_ReflectionProbe_0,
		Maps_FtueDeck_ReflectionProbe_1,
		Maps_Islands_IslandsMap,
		Maps_Islands_IslandsMapScene,
		Maps_Islands_IslandsMap_LM0_final,
		Maps_Islands_IslandsMap_LMA1_final,
		Maps_Islands_IslandsMap_LMA2_final,
		Maps_Islands_IslandsMap_LMA3_final,
		Maps_Islands_IslandsMap_LMA4_final,
		Maps_Islands_IslandsMap_LMA5_final,
		Maps_Islands_IslandsMap_NavMesh,
		Maps_Islands_IslandsMap_NavMesh_data,
		Maps_Islands_IslandsMap_mesh,
		Maps_Islands_LightingData,
		Maps_Islands_NavMesh_Navmesh,
		Maps_Islands_NavMesh,
		Maps_Islands_ReflectionProbe_0,
		Maps_Islands_ReflectionProbe_1,
		Maps_NewBR_LightingData,
		Maps_NewBR_NavMesh_Navmesh,
		Maps_NewBR_NewBRMap,
		Maps_NewBR_NewBRMapScene,
		Maps_NewBR_NewBRMap_LM0_final,
		Maps_NewBR_NewBRMap_LMA1_final,
		Maps_NewBR_NewBRMap_LMA2_final,
		Maps_NewBR_NewBRMap_LMA3_final,
		Maps_NewBR_NewBRMap_LMA4_final,
		Maps_NewBR_NewBRMap_NavMesh,
		Maps_NewBR_NewBRMap_NavMesh_data,
		Maps_NewBR_NewBRMap_mesh,
		Maps_NewBR_NewBRMap_skybox,
		Maps_NewBR_ReflectionProbe_0,
		Maps_NewBR_ReflectionProbe_1,
		Maps_MazeMayhem_MazeMayhem,
		Maps_MazeMayhem_MazeMayhemScene,
		Maps_MazeMayhem_MazeMayhem_LM0_final,
		Maps_MazeMayhem_MazeMayhem_LMA1_final,
		Maps_MazeMayhem_MazeMayhem_LMA2_final,
		Maps_MazeMayhem_MazeMayhem_NavMesh,
		Maps_MazeMayhem_MazeMayhem_NavMesh_data,
		Maps_MazeMayhem_MazeMayhem_mesh,
		Maps_MazeMayhem_NavMesh_Navmesh,
		Maps_Test_LightingData,
		Maps_Test_Lightmap_0_comp_dir,
		Maps_Test_Lightmap_0_comp_light,
		Maps_Test_Lightmap_1_comp_dir,
		Maps_Test_Lightmap_1_comp_light,
		Maps_Test_NavMesh,
		Maps_Test_ReflectionProbe_0,
		Maps_Test_ReflectionProbe_1,
		Maps_Test_SmallWilderness_NavMesh_data,
		Maps_Test_TestScene,
		Maps_Test_TestScene_NavMesh,
		Maps_Test_TestScene_NavMesh_data,
		Maps_Test_TestScene_Scene,
		Maps_Test_TestScene_mesh,
		Maps_District_District,
		Maps_District_DistrictScene,
		Maps_District_District_LM0_final,
		Maps_District_District_LMA1_final,
		Maps_District_District_LMA2_final,
		Maps_District_District_NavMesh,
		Maps_District_District_NavMesh_data,
		Maps_District_District_mesh,
		Maps_District_LightingData,
		Maps_District_Lightmap_0_comp_dir,
		Maps_District_Lightmap_0_comp_light,
		Maps_District_NavMesh_Navmesh,
		Maps_Battlelands_BattlelandsMap,
		Maps_Battlelands_BattlelandsMapScene,
		Maps_Battlelands_BattlelandsMap_NavMesh,
		Maps_Battlelands_BattlelandsMap_NavMesh_data,
		Maps_Battlelands_BattlelandsMap_mesh,
		Maps_Battlelands_LightingData,
		Maps_Battlelands_NavMesh,
		Maps_Battlelands_ReflectionProbe_0,
		Maps_Battlelands_ReflectionProbe_1
	}

	public enum AddressableLabel
	{
		Label_GenerateIds
	}

	public static class AddressablePathLookup
	{
		public static readonly string MapsBattlelands = "Maps/Battlelands";
		public static readonly string MapsDistrict = "Maps/District";
		public static readonly string MapsTest = "Maps/Test";
		public static readonly string MapsMazeMayhem = "Maps/MazeMayhem";
		public static readonly string MapsNewBR = "Maps/NewBR";
		public static readonly string MapsIslands = "Maps/Islands";
		public static readonly string MapsFtueDeck = "Maps/FtueDeck";
		public static readonly string CollectionsProfilePicture = "Collections/ProfilePicture";
		public static readonly string ConfigsSettings = "Configs/Settings";
		public static readonly string Configs = "Configs";
		public static readonly string Maps = "Maps";
		public static readonly string CollectionsCharacterSkins = "Collections/CharacterSkins";
		public static readonly string CollectionsWeaponSkins = "Collections/WeaponSkins";
		public static readonly string Timeline = "Timeline";
	}

	public static class AddressableConfigLookup
	{
		public static IList<AddressableConfig> Configs => _addressableConfigs;
		public static IList<string> Labels => _addressableLabels;

		public static AddressableConfig GetConfig(this AddressableId addressable)
		{
			return _addressableConfigs[(int) addressable];
		}

		public static IList<AddressableConfig> GetConfigs(this AddressableLabel label)
		{
			return _addressableLabelMap[_addressableLabels[(int) label]];
		}

		public static IList<AddressableConfig> GetConfigs(string label)
		{
			return _addressableLabelMap[label];
		}

		public static string ToLabelString(this AddressableLabel label)
		{
			return _addressableLabels[(int) label];
		}

		private static readonly IList<string> _addressableLabels = new List<string>
		{
			"GenerateIds"
		}.AsReadOnly();

		private static readonly IReadOnlyDictionary<string, IList<AddressableConfig>> _addressableLabelMap = new ReadOnlyDictionary<string, IList<AddressableConfig>>(new Dictionary<string, IList<AddressableConfig>>
		{
			{"GenerateIds", new List<AddressableConfig>
				{
					new AddressableConfig(0, "Maps/Battlelands/ReflectionProbe-1.exr", "Assets/AddressableResources/Maps/Battlelands/ReflectionProbe-1.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
					new AddressableConfig(1, "Maps/Battlelands/ReflectionProbe-0.exr", "Assets/AddressableResources/Maps/Battlelands/ReflectionProbe-0.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
					new AddressableConfig(2, "Maps/Battlelands/NavMesh.asset", "Assets/AddressableResources/Maps/Battlelands/NavMesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
					new AddressableConfig(3, "Maps/Battlelands/LightingData.asset", "Assets/AddressableResources/Maps/Battlelands/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(4, "Maps/Battlelands/BattlelandsMap_mesh.asset", "Assets/AddressableResources/Maps/Battlelands/BattlelandsMap_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(5, "Maps/Battlelands/BattlelandsMap_NavMesh_data.asset", "Assets/AddressableResources/Maps/Battlelands/BattlelandsMap_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(6, "Maps/Battlelands/BattlelandsMap_NavMesh.asset", "Assets/AddressableResources/Maps/Battlelands/BattlelandsMap_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
					new AddressableConfig(7, "Maps/Battlelands/BattlelandsMapScene.unity", "Assets/AddressableResources/Maps/Battlelands/BattlelandsMapScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
					new AddressableConfig(8, "Maps/Battlelands/BattlelandsMap.asset", "Assets/AddressableResources/Maps/Battlelands/BattlelandsMap.asset", typeof(MapAsset), new [] {"GenerateIds"}),
					new AddressableConfig(9, "Maps/District/NavMesh-Navmesh.asset", "Assets/AddressableResources/Maps/District/NavMesh-Navmesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
					new AddressableConfig(10, "Maps/District/Lightmap-0_comp_light.exr", "Assets/AddressableResources/Maps/District/Lightmap-0_comp_light.exr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(11, "Maps/District/Lightmap-0_comp_dir.png", "Assets/AddressableResources/Maps/District/Lightmap-0_comp_dir.png", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(12, "Maps/District/LightingData.asset", "Assets/AddressableResources/Maps/District/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(13, "Maps/District/District_mesh.asset", "Assets/AddressableResources/Maps/District/District_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(14, "Maps/District/District_NavMesh_data.asset", "Assets/AddressableResources/Maps/District/District_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(15, "Maps/District/District_NavMesh.asset", "Assets/AddressableResources/Maps/District/District_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
					new AddressableConfig(16, "Maps/District/District_LMA2_final.hdr", "Assets/AddressableResources/Maps/District/District_LMA2_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(17, "Maps/District/District_LMA1_final.hdr", "Assets/AddressableResources/Maps/District/District_LMA1_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(18, "Maps/District/District_LM0_final.hdr", "Assets/AddressableResources/Maps/District/District_LM0_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(19, "Maps/District/DistrictScene.unity", "Assets/AddressableResources/Maps/District/DistrictScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
					new AddressableConfig(20, "Maps/District/District.asset", "Assets/AddressableResources/Maps/District/District.asset", typeof(MapAsset), new [] {"GenerateIds"}),
					new AddressableConfig(21, "Maps/Test/TestScene_mesh.asset", "Assets/AddressableResources/Maps/Test/TestScene_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(22, "Maps/Test/TestScene_Scene.unity", "Assets/AddressableResources/Maps/Test/TestScene_Scene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
					new AddressableConfig(23, "Maps/Test/TestScene_NavMesh_data.asset", "Assets/AddressableResources/Maps/Test/TestScene_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(24, "Maps/Test/TestScene_NavMesh.asset", "Assets/AddressableResources/Maps/Test/TestScene_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
					new AddressableConfig(25, "Maps/Test/TestScene.asset", "Assets/AddressableResources/Maps/Test/TestScene.asset", typeof(MapAsset), new [] {"GenerateIds"}),
					new AddressableConfig(26, "Maps/Test/SmallWilderness_NavMesh_data.asset", "Assets/AddressableResources/Maps/Test/SmallWilderness_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(27, "Maps/Test/ReflectionProbe-1.exr", "Assets/AddressableResources/Maps/Test/ReflectionProbe-1.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
					new AddressableConfig(28, "Maps/Test/ReflectionProbe-0.exr", "Assets/AddressableResources/Maps/Test/ReflectionProbe-0.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
					new AddressableConfig(29, "Maps/Test/NavMesh.asset", "Assets/AddressableResources/Maps/Test/NavMesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
					new AddressableConfig(30, "Maps/Test/Lightmap-1_comp_light.exr", "Assets/AddressableResources/Maps/Test/Lightmap-1_comp_light.exr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(31, "Maps/Test/Lightmap-1_comp_dir.png", "Assets/AddressableResources/Maps/Test/Lightmap-1_comp_dir.png", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(32, "Maps/Test/Lightmap-0_comp_light.exr", "Assets/AddressableResources/Maps/Test/Lightmap-0_comp_light.exr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(33, "Maps/Test/Lightmap-0_comp_dir.png", "Assets/AddressableResources/Maps/Test/Lightmap-0_comp_dir.png", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(34, "Maps/Test/LightingData.asset", "Assets/AddressableResources/Maps/Test/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(35, "Maps/MazeMayhem/NavMesh-Navmesh.asset", "Assets/AddressableResources/Maps/MazeMayhem/NavMesh-Navmesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
					new AddressableConfig(36, "Maps/MazeMayhem/MazeMayhem_mesh.asset", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(37, "Maps/MazeMayhem/MazeMayhem_NavMesh_data.asset", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(38, "Maps/MazeMayhem/MazeMayhem_NavMesh.asset", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
					new AddressableConfig(39, "Maps/MazeMayhem/MazeMayhem_LMA2_final.hdr", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_LMA2_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(40, "Maps/MazeMayhem/MazeMayhem_LMA1_final.hdr", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_LMA1_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(41, "Maps/MazeMayhem/MazeMayhem_LM0_final.hdr", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_LM0_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(42, "Maps/MazeMayhem/MazeMayhemScene.unity", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhemScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
					new AddressableConfig(43, "Maps/MazeMayhem/MazeMayhem.asset", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem.asset", typeof(MapAsset), new [] {"GenerateIds"}),
					new AddressableConfig(44, "Maps/NewBR/ReflectionProbe-1.exr", "Assets/AddressableResources/Maps/NewBR/ReflectionProbe-1.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
					new AddressableConfig(45, "Maps/NewBR/ReflectionProbe-0.exr", "Assets/AddressableResources/Maps/NewBR/ReflectionProbe-0.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
					new AddressableConfig(46, "Maps/NewBR/NewBRMap_skybox.asset", "Assets/AddressableResources/Maps/NewBR/NewBRMap_skybox.asset", typeof(UnityEngine.Material), new [] {"GenerateIds"}),
					new AddressableConfig(47, "Maps/NewBR/NewBRMap_mesh.asset", "Assets/AddressableResources/Maps/NewBR/NewBRMap_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(48, "Maps/NewBR/NewBRMap_NavMesh_data.asset", "Assets/AddressableResources/Maps/NewBR/NewBRMap_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(49, "Maps/NewBR/NewBRMap_NavMesh.asset", "Assets/AddressableResources/Maps/NewBR/NewBRMap_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
					new AddressableConfig(50, "Maps/NewBR/NewBRMap_LMA4_final.hdr", "Assets/AddressableResources/Maps/NewBR/NewBRMap_LMA4_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(51, "Maps/NewBR/NewBRMap_LMA3_final.hdr", "Assets/AddressableResources/Maps/NewBR/NewBRMap_LMA3_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(52, "Maps/NewBR/NewBRMap_LMA2_final.hdr", "Assets/AddressableResources/Maps/NewBR/NewBRMap_LMA2_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(53, "Maps/NewBR/NewBRMap_LMA1_final.hdr", "Assets/AddressableResources/Maps/NewBR/NewBRMap_LMA1_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(54, "Maps/NewBR/NewBRMap_LM0_final.hdr", "Assets/AddressableResources/Maps/NewBR/NewBRMap_LM0_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(55, "Maps/NewBR/NewBRMapScene.unity", "Assets/AddressableResources/Maps/NewBR/NewBRMapScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
					new AddressableConfig(56, "Maps/NewBR/NewBRMap.asset", "Assets/AddressableResources/Maps/NewBR/NewBRMap.asset", typeof(MapAsset), new [] {"GenerateIds"}),
					new AddressableConfig(57, "Maps/NewBR/NavMesh-Navmesh.asset", "Assets/AddressableResources/Maps/NewBR/NavMesh-Navmesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
					new AddressableConfig(58, "Maps/NewBR/LightingData.asset", "Assets/AddressableResources/Maps/NewBR/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(59, "Maps/Islands/ReflectionProbe-1.exr", "Assets/AddressableResources/Maps/Islands/ReflectionProbe-1.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
					new AddressableConfig(60, "Maps/Islands/ReflectionProbe-0.exr", "Assets/AddressableResources/Maps/Islands/ReflectionProbe-0.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
					new AddressableConfig(61, "Maps/Islands/NavMesh.asset", "Assets/AddressableResources/Maps/Islands/NavMesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
					new AddressableConfig(62, "Maps/Islands/NavMesh-Navmesh.asset", "Assets/AddressableResources/Maps/Islands/NavMesh-Navmesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
					new AddressableConfig(63, "Maps/Islands/LightingData.asset", "Assets/AddressableResources/Maps/Islands/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(64, "Maps/Islands/IslandsMap_mesh.asset", "Assets/AddressableResources/Maps/Islands/IslandsMap_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(65, "Maps/Islands/IslandsMap_NavMesh_data.asset", "Assets/AddressableResources/Maps/Islands/IslandsMap_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(66, "Maps/Islands/IslandsMap_NavMesh.asset", "Assets/AddressableResources/Maps/Islands/IslandsMap_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
					new AddressableConfig(67, "Maps/Islands/IslandsMap_LMA5_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LMA5_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(68, "Maps/Islands/IslandsMap_LMA4_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LMA4_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(69, "Maps/Islands/IslandsMap_LMA3_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LMA3_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(70, "Maps/Islands/IslandsMap_LMA2_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LMA2_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(71, "Maps/Islands/IslandsMap_LMA1_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LMA1_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(72, "Maps/Islands/IslandsMap_LM0_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LM0_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(73, "Maps/Islands/IslandsMapScene.unity", "Assets/AddressableResources/Maps/Islands/IslandsMapScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
					new AddressableConfig(74, "Maps/Islands/IslandsMap.asset", "Assets/AddressableResources/Maps/Islands/IslandsMap.asset", typeof(MapAsset), new [] {"GenerateIds"}),
					new AddressableConfig(75, "Maps/FtueDeck/ReflectionProbe-1.exr", "Assets/AddressableResources/Maps/FtueDeck/ReflectionProbe-1.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
					new AddressableConfig(76, "Maps/FtueDeck/ReflectionProbe-0.exr", "Assets/AddressableResources/Maps/FtueDeck/ReflectionProbe-0.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
					new AddressableConfig(77, "Maps/FtueDeck/NavMesh.asset", "Assets/AddressableResources/Maps/FtueDeck/NavMesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
					new AddressableConfig(78, "Maps/FtueDeck/LightingData.asset", "Assets/AddressableResources/Maps/FtueDeck/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(79, "Maps/FtueDeck/FtueDeck_mesh.asset", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(80, "Maps/FtueDeck/FtueDeck_NavMesh_data.asset", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
					new AddressableConfig(81, "Maps/FtueDeck/FtueDeck_NavMesh.asset", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
					new AddressableConfig(82, "Maps/FtueDeck/FtueDeck_LMA3_final.hdr", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_LMA3_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(83, "Maps/FtueDeck/FtueDeck_LMA2_final.hdr", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_LMA2_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(84, "Maps/FtueDeck/FtueDeck_LMA1_final.hdr", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_LMA1_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(85, "Maps/FtueDeck/FtueDeck_LM0_final.hdr", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_LM0_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
					new AddressableConfig(86, "Maps/FtueDeck/FtueDeckScene.unity", "Assets/AddressableResources/Maps/FtueDeck/FtueDeckScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
					new AddressableConfig(87, "Maps/FtueDeck/FtueDeck.asset", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck.asset", typeof(MapAsset), new [] {"GenerateIds"}),
					new AddressableConfig(88, "Collections/ProfilePicture/AvatarCollectableConfigs.asset", "Assets/AddressableResources/Collections/ProfilePicture/AvatarCollectableConfigs.asset", typeof(FirstLight.Game.Configs.AvatarCollectableConfigs), new [] {"ScriptableObjectsOnly","GenerateIds"}),
					new AddressableConfig(89, "Configs/Settings/UiConfigs.asset", "Assets/AddressableResources/Configs/Settings/UiConfigs.asset", typeof(FirstLight.UiService.UiConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(90, "Configs/Settings/SimulationConfig.asset", "Assets/AddressableResources/Configs/Settings/SimulationConfig.asset", typeof(SimulationConfigAsset), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(91, "Configs/Settings/QuantumRunnerConfigs.asset", "Assets/AddressableResources/Configs/Settings/QuantumRunnerConfigs.asset", typeof(FirstLight.Game.Configs.QuantumRunnerConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(92, "Configs/Settings/PhotonServerSettings.asset", "Assets/AddressableResources/Configs/Settings/PhotonServerSettings.asset", typeof(PhotonServerSettings), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(93, "Configs/Settings/Deterministic Config.asset", "Assets/AddressableResources/Configs/Settings/Deterministic Config.asset", typeof(DeterministicSessionConfigAsset), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(94, "Configs/Settings/AssetResources.asset", "Assets/AddressableResources/Configs/Settings/AssetResources.asset", typeof(Quantum.AssetResourceContainer), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(95, "Configs/WeaponConfigs.asset", "Assets/AddressableResources/Configs/WeaponConfigs.asset", typeof(FirstLight.Game.Configs.WeaponConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(96, "Configs/VideoAssetConfigs.asset", "Assets/AddressableResources/Configs/VideoAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.VideoAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(97, "Configs/VfxConfigs.asset", "Assets/AddressableResources/Configs/VfxConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.VfxAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(98, "Configs/UpgradeDataConfigs.asset", "Assets/AddressableResources/Configs/UpgradeDataConfigs.asset", typeof(FirstLight.Game.Configs.UpgradeDataConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(99, "Configs/TutorialRewardConfigs.asset", "Assets/AddressableResources/Configs/TutorialRewardConfigs.asset", typeof(FirstLight.Game.Configs.TutorialRewardConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(100, "Configs/TutorialBattlePassConfigs.asset", "Assets/AddressableResources/Configs/TutorialBattlePassConfigs.asset", typeof(FirstLight.Game.Configs.TutorialBattlePassConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(101, "Configs/TrophyRewardConfigs.asset", "Assets/AddressableResources/Configs/TrophyRewardConfigs.asset", typeof(FirstLight.Game.Configs.TrophyRewardConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(102, "Configs/StatConfigs.asset", "Assets/AddressableResources/Configs/StatConfigs.asset", typeof(FirstLight.Game.Configs.StatConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(103, "Configs/SpriteAssetConfigs.asset", "Assets/AddressableResources/Configs/SpriteAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SpriteAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(104, "Configs/SpecialMoveAssetConfigs.asset", "Assets/AddressableResources/Configs/SpecialMoveAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SpecialMoveAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(105, "Configs/SpecialConfigs.asset", "Assets/AddressableResources/Configs/SpecialConfigs.asset", typeof(FirstLight.Game.Configs.SpecialConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(106, "Configs/ShrinkingCircleConfigs.asset", "Assets/AddressableResources/Configs/ShrinkingCircleConfigs.asset", typeof(FirstLight.Game.Configs.ShrinkingCircleConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(107, "Configs/ScrapConfigs.asset", "Assets/AddressableResources/Configs/ScrapConfigs.asset", typeof(FirstLight.Game.Configs.ScrapConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(108, "Configs/SceneAssetConfigs.asset", "Assets/AddressableResources/Configs/SceneAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SceneAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(109, "Configs/ResourcePoolConfigs.asset", "Assets/AddressableResources/Configs/ResourcePoolConfigs.asset", typeof(FirstLight.Game.Configs.ResourcePoolConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(110, "Configs/RepairDataConfigs.asset", "Assets/AddressableResources/Configs/RepairDataConfigs.asset", typeof(FirstLight.Game.Configs.RepairDataConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(111, "Configs/RarityDataConfigs.asset", "Assets/AddressableResources/Configs/RarityDataConfigs.asset", typeof(FirstLight.Game.Configs.RarityDataConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(112, "Configs/QuantumPrototypeAssetConfigs.asset", "Assets/AddressableResources/Configs/QuantumPrototypeAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.QuantumPrototypeAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(113, "Configs/PlayerRankAssetConfigs.asset", "Assets/AddressableResources/Configs/PlayerRankAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.PlayerRankAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(114, "Configs/PlayerLevelConfigs.asset", "Assets/AddressableResources/Configs/PlayerLevelConfigs.asset", typeof(FirstLight.Game.Configs.PlayerLevelConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(115, "Configs/MutatorConfigs.asset", "Assets/AddressableResources/Configs/MutatorConfigs.asset", typeof(FirstLight.Game.Configs.MutatorConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(116, "Configs/MaterialVfxConfigs.asset", "Assets/AddressableResources/Configs/MaterialVfxConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.MaterialVfxConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(117, "Configs/MaterialDataConfigs.asset", "Assets/AddressableResources/Configs/MaterialDataConfigs.asset", typeof(FirstLight.Game.Configs.MaterialDataConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(118, "Configs/MatchmakingAndRoomConfigs.asset", "Assets/AddressableResources/Configs/MatchmakingAndRoomConfigs.asset", typeof(FirstLight.Game.Configs.MatchmakingAndRoomConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(119, "Configs/MatchRewardConfigs.asset", "Assets/AddressableResources/Configs/MatchRewardConfigs.asset", typeof(FirstLight.Game.Configs.MatchRewardConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(120, "Configs/MapGridConfigs.asset", "Assets/AddressableResources/Configs/MapGridConfigs.asset", typeof(FirstLight.Game.Configs.MapGridConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(121, "Configs/ManufacturerDataConfigs.asset", "Assets/AddressableResources/Configs/ManufacturerDataConfigs.asset", typeof(FirstLight.Game.Configs.ManufacturerDataConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(122, "Configs/MainMenuCharacterAnimationConfigs.asset", "Assets/AddressableResources/Configs/MainMenuCharacterAnimationConfigs.asset", typeof(FirstLight.Game.Configs.MainMenuCharacterAnimationConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(123, "Configs/MainMenuAssetConfigs.asset", "Assets/AddressableResources/Configs/MainMenuAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.MainMenuAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(124, "Configs/LiveopsSegmentActionConfigs.asset", "Assets/AddressableResources/Configs/LiveopsSegmentActionConfigs.asset", typeof(FirstLight.Game.Configs.LiveopsSegmentActionConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(125, "Configs/LiveopsFeatureFlagConfigs.asset", "Assets/AddressableResources/Configs/LiveopsFeatureFlagConfigs.asset", typeof(FirstLight.Game.Configs.LiveopsFeatureFlagConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(126, "Configs/IndicatorVfxAssetConfigs.asset", "Assets/AddressableResources/Configs/IndicatorVfxAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.IndicatorVfxAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(127, "Configs/GraphicsConfig.asset", "Assets/AddressableResources/Configs/GraphicsConfig.asset", typeof(FirstLight.Game.Configs.GraphicsConfig), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(128, "Configs/GradeDataConfigs.asset", "Assets/AddressableResources/Configs/GradeDataConfigs.asset", typeof(FirstLight.Game.Configs.GradeDataConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(129, "Configs/GameModeRotationConfigs.asset", "Assets/AddressableResources/Configs/GameModeRotationConfigs.asset", typeof(FirstLight.Game.Configs.GameModeRotationConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(130, "Configs/GameModeConfigs.asset", "Assets/AddressableResources/Configs/GameModeConfigs.asset", typeof(FirstLight.Game.Configs.GameModeConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(131, "Configs/GameConfigs.asset", "Assets/AddressableResources/Configs/GameConfigs.asset", typeof(FirstLight.Game.Configs.GameConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(132, "Configs/FuseConfigs.asset", "Assets/AddressableResources/Configs/FuseConfigs.asset", typeof(FirstLight.Game.Configs.FuseConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(133, "Configs/FactionDataConfigs.asset", "Assets/AddressableResources/Configs/FactionDataConfigs.asset", typeof(FirstLight.Game.Configs.FactionDataConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(134, "Configs/EquipmentStatConfigs.asset", "Assets/AddressableResources/Configs/EquipmentStatConfigs.asset", typeof(FirstLight.Game.Configs.EquipmentStatConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(135, "Configs/EquipmentRewardConfigs.asset", "Assets/AddressableResources/Configs/EquipmentRewardConfigs.asset", typeof(FirstLight.Game.Configs.EquipmentRewardConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(136, "Configs/EquipmentRarityAssetConfigs.asset", "Assets/AddressableResources/Configs/EquipmentRarityAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.EquipmentRarityAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(137, "Configs/EquipmentMaterialStatConfigs.asset", "Assets/AddressableResources/Configs/EquipmentMaterialStatConfigs.asset", typeof(FirstLight.Game.Configs.EquipmentMaterialStatConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(138, "Configs/EditionDataConfigs.asset", "Assets/AddressableResources/Configs/EditionDataConfigs.asset", typeof(FirstLight.Game.Configs.EditionDataConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(139, "Configs/DummyAssetConfigs.asset", "Assets/AddressableResources/Configs/DummyAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.DummyAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(140, "Configs/DestructibleConfigs.asset", "Assets/AddressableResources/Configs/DestructibleConfigs.asset", typeof(FirstLight.Game.Configs.DestructibleConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(141, "Configs/CustomAssetConfigs.asset", "Assets/AddressableResources/Configs/CustomAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.CustomAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(142, "Configs/ConsumableConfigs.asset", "Assets/AddressableResources/Configs/ConsumableConfigs.asset", typeof(FirstLight.Game.Configs.ConsumableConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(143, "Configs/ChestConfigs.asset", "Assets/AddressableResources/Configs/ChestConfigs.asset", typeof(FirstLight.Game.Configs.ChestConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(144, "Configs/BotDifficultyConfigs.asset", "Assets/AddressableResources/Configs/BotDifficultyConfigs.asset", typeof(FirstLight.Game.Configs.BotDifficultyConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(145, "Configs/BotConfigs.asset", "Assets/AddressableResources/Configs/BotConfigs.asset", typeof(FirstLight.Game.Configs.BotConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(146, "Configs/BattlePassConfigs.asset", "Assets/AddressableResources/Configs/BattlePassConfigs.asset", typeof(FirstLight.Game.Configs.BattlePassConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(147, "Configs/BaseEquipmentStatConfigs.asset", "Assets/AddressableResources/Configs/BaseEquipmentStatConfigs.asset", typeof(FirstLight.Game.Configs.BaseEquipmentStatConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(148, "Configs/AudioWeaponConfigs.asset", "Assets/AddressableResources/Configs/AudioWeaponConfigs.asset", typeof(FirstLight.Game.Configs.AudioWeaponConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(149, "Configs/AudioSharedAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioSharedAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioSharedAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(150, "Configs/AudioMixerConfigs.asset", "Assets/AddressableResources/Configs/AudioMixerConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioMixerConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(151, "Configs/AudioMatchAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioMatchAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioMatchAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(152, "Configs/AudioMainMenuAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioMainMenuAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioMainMenuAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(153, "Configs/AdventureAssetConfigs.asset", "Assets/AddressableResources/Configs/AdventureAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.MatchAssetConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(154, "Configs/AdjectiveDataConfigs.asset", "Assets/AddressableResources/Configs/AdjectiveDataConfigs.asset", typeof(FirstLight.Game.Configs.AdjectiveDataConfigs), new [] {"Quantum","GenerateIds"}),
					new AddressableConfig(155, "Maps/QuantumMapConfigs.asset", "Assets/AddressableResources/Maps/QuantumMapConfigs.asset", typeof(FirstLight.Game.Configs.MapConfigs), new [] {"GenerateIds"}),
					new AddressableConfig(156, "Maps/MapAssetConfigs.asset", "Assets/AddressableResources/Maps/MapAssetConfigs.asset", typeof(FirstLight.Game.Configs.MapAssetConfigs), new [] {"GenerateIds"}),
					new AddressableConfig(157, "Collections/CharacterSkins/Config.asset", "Assets/AddressableResources/Collections/CharacterSkins/Config.asset", typeof(FirstLight.Game.Configs.CharacterSkinConfigs), new [] {"ScriptableObjectsOnly","GenerateIds"}),
					new AddressableConfig(158, "Collections/WeaponSkins/Config.asset", "Assets/AddressableResources/Collections/WeaponSkins/Config.asset", typeof(FirstLight.Game.Configs.Collection.WeaponSkinsConfigContainer), new [] {"ScriptableObjectsOnly","GenerateIds"}),
					new AddressableConfig(159, "Timeline/FtueTimeline.prefab", "Assets/AddressableResources/Timeline/FtueTimeline.prefab", typeof(UnityEngine.GameObject), new [] {"GenerateIds"}),
				}.AsReadOnly()}
		});

		private static readonly IList<AddressableConfig> _addressableConfigs = new List<AddressableConfig>
		{
			new AddressableConfig(0, "Timeline/FtueTimeline.prefab", "Assets/AddressableResources/Timeline/FtueTimeline.prefab", typeof(UnityEngine.GameObject), new [] {"GenerateIds"}),
			new AddressableConfig(1, "Collections/WeaponSkins/Config.asset", "Assets/AddressableResources/Collections/WeaponSkins/Config.asset", typeof(FirstLight.Game.Configs.Collection.WeaponSkinsConfigContainer), new [] {"ScriptableObjectsOnly","GenerateIds"}),
			new AddressableConfig(2, "Collections/CharacterSkins/Config.asset", "Assets/AddressableResources/Collections/CharacterSkins/Config.asset", typeof(FirstLight.Game.Configs.CharacterSkinConfigs), new [] {"ScriptableObjectsOnly","GenerateIds"}),
			new AddressableConfig(3, "Maps/MapAssetConfigs.asset", "Assets/AddressableResources/Maps/MapAssetConfigs.asset", typeof(FirstLight.Game.Configs.MapAssetConfigs), new [] {"GenerateIds"}),
			new AddressableConfig(4, "Maps/QuantumMapConfigs.asset", "Assets/AddressableResources/Maps/QuantumMapConfigs.asset", typeof(FirstLight.Game.Configs.MapConfigs), new [] {"GenerateIds"}),
			new AddressableConfig(5, "Configs/AdjectiveDataConfigs.asset", "Assets/AddressableResources/Configs/AdjectiveDataConfigs.asset", typeof(FirstLight.Game.Configs.AdjectiveDataConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(6, "Configs/AdventureAssetConfigs.asset", "Assets/AddressableResources/Configs/AdventureAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.MatchAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(7, "Configs/AudioMainMenuAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioMainMenuAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioMainMenuAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(8, "Configs/AudioMatchAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioMatchAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioMatchAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(9, "Configs/AudioMixerConfigs.asset", "Assets/AddressableResources/Configs/AudioMixerConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioMixerConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(10, "Configs/AudioSharedAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioSharedAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioSharedAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(11, "Configs/AudioWeaponConfigs.asset", "Assets/AddressableResources/Configs/AudioWeaponConfigs.asset", typeof(FirstLight.Game.Configs.AudioWeaponConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(12, "Configs/BaseEquipmentStatConfigs.asset", "Assets/AddressableResources/Configs/BaseEquipmentStatConfigs.asset", typeof(FirstLight.Game.Configs.BaseEquipmentStatConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(13, "Configs/BattlePassConfigs.asset", "Assets/AddressableResources/Configs/BattlePassConfigs.asset", typeof(FirstLight.Game.Configs.BattlePassConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(14, "Configs/BotConfigs.asset", "Assets/AddressableResources/Configs/BotConfigs.asset", typeof(FirstLight.Game.Configs.BotConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(15, "Configs/BotDifficultyConfigs.asset", "Assets/AddressableResources/Configs/BotDifficultyConfigs.asset", typeof(FirstLight.Game.Configs.BotDifficultyConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(16, "Configs/ChestConfigs.asset", "Assets/AddressableResources/Configs/ChestConfigs.asset", typeof(FirstLight.Game.Configs.ChestConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(17, "Configs/ConsumableConfigs.asset", "Assets/AddressableResources/Configs/ConsumableConfigs.asset", typeof(FirstLight.Game.Configs.ConsumableConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(18, "Configs/CustomAssetConfigs.asset", "Assets/AddressableResources/Configs/CustomAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.CustomAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(19, "Configs/DestructibleConfigs.asset", "Assets/AddressableResources/Configs/DestructibleConfigs.asset", typeof(FirstLight.Game.Configs.DestructibleConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(20, "Configs/DummyAssetConfigs.asset", "Assets/AddressableResources/Configs/DummyAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.DummyAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(21, "Configs/EditionDataConfigs.asset", "Assets/AddressableResources/Configs/EditionDataConfigs.asset", typeof(FirstLight.Game.Configs.EditionDataConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(22, "Configs/EquipmentMaterialStatConfigs.asset", "Assets/AddressableResources/Configs/EquipmentMaterialStatConfigs.asset", typeof(FirstLight.Game.Configs.EquipmentMaterialStatConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(23, "Configs/EquipmentRarityAssetConfigs.asset", "Assets/AddressableResources/Configs/EquipmentRarityAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.EquipmentRarityAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(24, "Configs/EquipmentRewardConfigs.asset", "Assets/AddressableResources/Configs/EquipmentRewardConfigs.asset", typeof(FirstLight.Game.Configs.EquipmentRewardConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(25, "Configs/EquipmentStatConfigs.asset", "Assets/AddressableResources/Configs/EquipmentStatConfigs.asset", typeof(FirstLight.Game.Configs.EquipmentStatConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(26, "Configs/FactionDataConfigs.asset", "Assets/AddressableResources/Configs/FactionDataConfigs.asset", typeof(FirstLight.Game.Configs.FactionDataConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(27, "Configs/FuseConfigs.asset", "Assets/AddressableResources/Configs/FuseConfigs.asset", typeof(FirstLight.Game.Configs.FuseConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(28, "Configs/GameConfigs.asset", "Assets/AddressableResources/Configs/GameConfigs.asset", typeof(FirstLight.Game.Configs.GameConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(29, "Configs/GameModeConfigs.asset", "Assets/AddressableResources/Configs/GameModeConfigs.asset", typeof(FirstLight.Game.Configs.GameModeConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(30, "Configs/GameModeRotationConfigs.asset", "Assets/AddressableResources/Configs/GameModeRotationConfigs.asset", typeof(FirstLight.Game.Configs.GameModeRotationConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(31, "Configs/GradeDataConfigs.asset", "Assets/AddressableResources/Configs/GradeDataConfigs.asset", typeof(FirstLight.Game.Configs.GradeDataConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(32, "Configs/GraphicsConfig.asset", "Assets/AddressableResources/Configs/GraphicsConfig.asset", typeof(FirstLight.Game.Configs.GraphicsConfig), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(33, "Configs/IndicatorVfxAssetConfigs.asset", "Assets/AddressableResources/Configs/IndicatorVfxAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.IndicatorVfxAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(34, "Configs/LiveopsFeatureFlagConfigs.asset", "Assets/AddressableResources/Configs/LiveopsFeatureFlagConfigs.asset", typeof(FirstLight.Game.Configs.LiveopsFeatureFlagConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(35, "Configs/LiveopsSegmentActionConfigs.asset", "Assets/AddressableResources/Configs/LiveopsSegmentActionConfigs.asset", typeof(FirstLight.Game.Configs.LiveopsSegmentActionConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(36, "Configs/MainMenuAssetConfigs.asset", "Assets/AddressableResources/Configs/MainMenuAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.MainMenuAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(37, "Configs/MainMenuCharacterAnimationConfigs.asset", "Assets/AddressableResources/Configs/MainMenuCharacterAnimationConfigs.asset", typeof(FirstLight.Game.Configs.MainMenuCharacterAnimationConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(38, "Configs/ManufacturerDataConfigs.asset", "Assets/AddressableResources/Configs/ManufacturerDataConfigs.asset", typeof(FirstLight.Game.Configs.ManufacturerDataConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(39, "Configs/MapGridConfigs.asset", "Assets/AddressableResources/Configs/MapGridConfigs.asset", typeof(FirstLight.Game.Configs.MapGridConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(40, "Configs/MatchRewardConfigs.asset", "Assets/AddressableResources/Configs/MatchRewardConfigs.asset", typeof(FirstLight.Game.Configs.MatchRewardConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(41, "Configs/MatchmakingAndRoomConfigs.asset", "Assets/AddressableResources/Configs/MatchmakingAndRoomConfigs.asset", typeof(FirstLight.Game.Configs.MatchmakingAndRoomConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(42, "Configs/MaterialDataConfigs.asset", "Assets/AddressableResources/Configs/MaterialDataConfigs.asset", typeof(FirstLight.Game.Configs.MaterialDataConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(43, "Configs/MaterialVfxConfigs.asset", "Assets/AddressableResources/Configs/MaterialVfxConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.MaterialVfxConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(44, "Configs/MutatorConfigs.asset", "Assets/AddressableResources/Configs/MutatorConfigs.asset", typeof(FirstLight.Game.Configs.MutatorConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(45, "Configs/PlayerLevelConfigs.asset", "Assets/AddressableResources/Configs/PlayerLevelConfigs.asset", typeof(FirstLight.Game.Configs.PlayerLevelConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(46, "Configs/PlayerRankAssetConfigs.asset", "Assets/AddressableResources/Configs/PlayerRankAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.PlayerRankAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(47, "Configs/QuantumPrototypeAssetConfigs.asset", "Assets/AddressableResources/Configs/QuantumPrototypeAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.QuantumPrototypeAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(48, "Configs/RarityDataConfigs.asset", "Assets/AddressableResources/Configs/RarityDataConfigs.asset", typeof(FirstLight.Game.Configs.RarityDataConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(49, "Configs/RepairDataConfigs.asset", "Assets/AddressableResources/Configs/RepairDataConfigs.asset", typeof(FirstLight.Game.Configs.RepairDataConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(50, "Configs/ResourcePoolConfigs.asset", "Assets/AddressableResources/Configs/ResourcePoolConfigs.asset", typeof(FirstLight.Game.Configs.ResourcePoolConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(51, "Configs/SceneAssetConfigs.asset", "Assets/AddressableResources/Configs/SceneAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SceneAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(52, "Configs/ScrapConfigs.asset", "Assets/AddressableResources/Configs/ScrapConfigs.asset", typeof(FirstLight.Game.Configs.ScrapConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(53, "Configs/ShrinkingCircleConfigs.asset", "Assets/AddressableResources/Configs/ShrinkingCircleConfigs.asset", typeof(FirstLight.Game.Configs.ShrinkingCircleConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(54, "Configs/SpecialConfigs.asset", "Assets/AddressableResources/Configs/SpecialConfigs.asset", typeof(FirstLight.Game.Configs.SpecialConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(55, "Configs/SpecialMoveAssetConfigs.asset", "Assets/AddressableResources/Configs/SpecialMoveAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SpecialMoveAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(56, "Configs/SpriteAssetConfigs.asset", "Assets/AddressableResources/Configs/SpriteAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SpriteAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(57, "Configs/StatConfigs.asset", "Assets/AddressableResources/Configs/StatConfigs.asset", typeof(FirstLight.Game.Configs.StatConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(58, "Configs/TrophyRewardConfigs.asset", "Assets/AddressableResources/Configs/TrophyRewardConfigs.asset", typeof(FirstLight.Game.Configs.TrophyRewardConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(59, "Configs/TutorialBattlePassConfigs.asset", "Assets/AddressableResources/Configs/TutorialBattlePassConfigs.asset", typeof(FirstLight.Game.Configs.TutorialBattlePassConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(60, "Configs/TutorialRewardConfigs.asset", "Assets/AddressableResources/Configs/TutorialRewardConfigs.asset", typeof(FirstLight.Game.Configs.TutorialRewardConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(61, "Configs/UpgradeDataConfigs.asset", "Assets/AddressableResources/Configs/UpgradeDataConfigs.asset", typeof(FirstLight.Game.Configs.UpgradeDataConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(62, "Configs/VfxConfigs.asset", "Assets/AddressableResources/Configs/VfxConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.VfxAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(63, "Configs/VideoAssetConfigs.asset", "Assets/AddressableResources/Configs/VideoAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.VideoAssetConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(64, "Configs/WeaponConfigs.asset", "Assets/AddressableResources/Configs/WeaponConfigs.asset", typeof(FirstLight.Game.Configs.WeaponConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(65, "Configs/Settings/AssetResources.asset", "Assets/AddressableResources/Configs/Settings/AssetResources.asset", typeof(Quantum.AssetResourceContainer), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(66, "Configs/Settings/Deterministic Config.asset", "Assets/AddressableResources/Configs/Settings/Deterministic Config.asset", typeof(DeterministicSessionConfigAsset), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(67, "Configs/Settings/PhotonServerSettings.asset", "Assets/AddressableResources/Configs/Settings/PhotonServerSettings.asset", typeof(PhotonServerSettings), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(68, "Configs/Settings/QuantumRunnerConfigs.asset", "Assets/AddressableResources/Configs/Settings/QuantumRunnerConfigs.asset", typeof(FirstLight.Game.Configs.QuantumRunnerConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(69, "Configs/Settings/SimulationConfig.asset", "Assets/AddressableResources/Configs/Settings/SimulationConfig.asset", typeof(SimulationConfigAsset), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(70, "Configs/Settings/UiConfigs.asset", "Assets/AddressableResources/Configs/Settings/UiConfigs.asset", typeof(FirstLight.UiService.UiConfigs), new [] {"Quantum","GenerateIds"}),
			new AddressableConfig(71, "Collections/ProfilePicture/AvatarCollectableConfigs.asset", "Assets/AddressableResources/Collections/ProfilePicture/AvatarCollectableConfigs.asset", typeof(FirstLight.Game.Configs.AvatarCollectableConfigs), new [] {"ScriptableObjectsOnly","GenerateIds"}),
			new AddressableConfig(72, "Maps/FtueDeck/FtueDeck.asset", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck.asset", typeof(MapAsset), new [] {"GenerateIds"}),
			new AddressableConfig(73, "Maps/FtueDeck/FtueDeckScene.unity", "Assets/AddressableResources/Maps/FtueDeck/FtueDeckScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
			new AddressableConfig(74, "Maps/FtueDeck/FtueDeck_LM0_final.hdr", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_LM0_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(75, "Maps/FtueDeck/FtueDeck_LMA1_final.hdr", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_LMA1_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(76, "Maps/FtueDeck/FtueDeck_LMA2_final.hdr", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_LMA2_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(77, "Maps/FtueDeck/FtueDeck_LMA3_final.hdr", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_LMA3_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(78, "Maps/FtueDeck/FtueDeck_NavMesh.asset", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
			new AddressableConfig(79, "Maps/FtueDeck/FtueDeck_NavMesh_data.asset", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(80, "Maps/FtueDeck/FtueDeck_mesh.asset", "Assets/AddressableResources/Maps/FtueDeck/FtueDeck_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(81, "Maps/FtueDeck/LightingData.asset", "Assets/AddressableResources/Maps/FtueDeck/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(82, "Maps/FtueDeck/NavMesh.asset", "Assets/AddressableResources/Maps/FtueDeck/NavMesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
			new AddressableConfig(83, "Maps/FtueDeck/ReflectionProbe-0.exr", "Assets/AddressableResources/Maps/FtueDeck/ReflectionProbe-0.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
			new AddressableConfig(84, "Maps/FtueDeck/ReflectionProbe-1.exr", "Assets/AddressableResources/Maps/FtueDeck/ReflectionProbe-1.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
			new AddressableConfig(85, "Maps/Islands/IslandsMap.asset", "Assets/AddressableResources/Maps/Islands/IslandsMap.asset", typeof(MapAsset), new [] {"GenerateIds"}),
			new AddressableConfig(86, "Maps/Islands/IslandsMapScene.unity", "Assets/AddressableResources/Maps/Islands/IslandsMapScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
			new AddressableConfig(87, "Maps/Islands/IslandsMap_LM0_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LM0_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(88, "Maps/Islands/IslandsMap_LMA1_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LMA1_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(89, "Maps/Islands/IslandsMap_LMA2_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LMA2_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(90, "Maps/Islands/IslandsMap_LMA3_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LMA3_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(91, "Maps/Islands/IslandsMap_LMA4_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LMA4_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(92, "Maps/Islands/IslandsMap_LMA5_final.hdr", "Assets/AddressableResources/Maps/Islands/IslandsMap_LMA5_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(93, "Maps/Islands/IslandsMap_NavMesh.asset", "Assets/AddressableResources/Maps/Islands/IslandsMap_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
			new AddressableConfig(94, "Maps/Islands/IslandsMap_NavMesh_data.asset", "Assets/AddressableResources/Maps/Islands/IslandsMap_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(95, "Maps/Islands/IslandsMap_mesh.asset", "Assets/AddressableResources/Maps/Islands/IslandsMap_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(96, "Maps/Islands/LightingData.asset", "Assets/AddressableResources/Maps/Islands/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(97, "Maps/Islands/NavMesh-Navmesh.asset", "Assets/AddressableResources/Maps/Islands/NavMesh-Navmesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
			new AddressableConfig(98, "Maps/Islands/NavMesh.asset", "Assets/AddressableResources/Maps/Islands/NavMesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
			new AddressableConfig(99, "Maps/Islands/ReflectionProbe-0.exr", "Assets/AddressableResources/Maps/Islands/ReflectionProbe-0.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
			new AddressableConfig(100, "Maps/Islands/ReflectionProbe-1.exr", "Assets/AddressableResources/Maps/Islands/ReflectionProbe-1.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
			new AddressableConfig(101, "Maps/NewBR/LightingData.asset", "Assets/AddressableResources/Maps/NewBR/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(102, "Maps/NewBR/NavMesh-Navmesh.asset", "Assets/AddressableResources/Maps/NewBR/NavMesh-Navmesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
			new AddressableConfig(103, "Maps/NewBR/NewBRMap.asset", "Assets/AddressableResources/Maps/NewBR/NewBRMap.asset", typeof(MapAsset), new [] {"GenerateIds"}),
			new AddressableConfig(104, "Maps/NewBR/NewBRMapScene.unity", "Assets/AddressableResources/Maps/NewBR/NewBRMapScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
			new AddressableConfig(105, "Maps/NewBR/NewBRMap_LM0_final.hdr", "Assets/AddressableResources/Maps/NewBR/NewBRMap_LM0_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(106, "Maps/NewBR/NewBRMap_LMA1_final.hdr", "Assets/AddressableResources/Maps/NewBR/NewBRMap_LMA1_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(107, "Maps/NewBR/NewBRMap_LMA2_final.hdr", "Assets/AddressableResources/Maps/NewBR/NewBRMap_LMA2_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(108, "Maps/NewBR/NewBRMap_LMA3_final.hdr", "Assets/AddressableResources/Maps/NewBR/NewBRMap_LMA3_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(109, "Maps/NewBR/NewBRMap_LMA4_final.hdr", "Assets/AddressableResources/Maps/NewBR/NewBRMap_LMA4_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(110, "Maps/NewBR/NewBRMap_NavMesh.asset", "Assets/AddressableResources/Maps/NewBR/NewBRMap_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
			new AddressableConfig(111, "Maps/NewBR/NewBRMap_NavMesh_data.asset", "Assets/AddressableResources/Maps/NewBR/NewBRMap_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(112, "Maps/NewBR/NewBRMap_mesh.asset", "Assets/AddressableResources/Maps/NewBR/NewBRMap_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(113, "Maps/NewBR/NewBRMap_skybox.asset", "Assets/AddressableResources/Maps/NewBR/NewBRMap_skybox.asset", typeof(UnityEngine.Material), new [] {"GenerateIds"}),
			new AddressableConfig(114, "Maps/NewBR/ReflectionProbe-0.exr", "Assets/AddressableResources/Maps/NewBR/ReflectionProbe-0.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
			new AddressableConfig(115, "Maps/NewBR/ReflectionProbe-1.exr", "Assets/AddressableResources/Maps/NewBR/ReflectionProbe-1.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
			new AddressableConfig(116, "Maps/MazeMayhem/MazeMayhem.asset", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem.asset", typeof(MapAsset), new [] {"GenerateIds"}),
			new AddressableConfig(117, "Maps/MazeMayhem/MazeMayhemScene.unity", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhemScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
			new AddressableConfig(118, "Maps/MazeMayhem/MazeMayhem_LM0_final.hdr", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_LM0_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(119, "Maps/MazeMayhem/MazeMayhem_LMA1_final.hdr", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_LMA1_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(120, "Maps/MazeMayhem/MazeMayhem_LMA2_final.hdr", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_LMA2_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(121, "Maps/MazeMayhem/MazeMayhem_NavMesh.asset", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
			new AddressableConfig(122, "Maps/MazeMayhem/MazeMayhem_NavMesh_data.asset", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(123, "Maps/MazeMayhem/MazeMayhem_mesh.asset", "Assets/AddressableResources/Maps/MazeMayhem/MazeMayhem_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(124, "Maps/MazeMayhem/NavMesh-Navmesh.asset", "Assets/AddressableResources/Maps/MazeMayhem/NavMesh-Navmesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
			new AddressableConfig(125, "Maps/Test/LightingData.asset", "Assets/AddressableResources/Maps/Test/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(126, "Maps/Test/Lightmap-0_comp_dir.png", "Assets/AddressableResources/Maps/Test/Lightmap-0_comp_dir.png", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(127, "Maps/Test/Lightmap-0_comp_light.exr", "Assets/AddressableResources/Maps/Test/Lightmap-0_comp_light.exr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(128, "Maps/Test/Lightmap-1_comp_dir.png", "Assets/AddressableResources/Maps/Test/Lightmap-1_comp_dir.png", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(129, "Maps/Test/Lightmap-1_comp_light.exr", "Assets/AddressableResources/Maps/Test/Lightmap-1_comp_light.exr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(130, "Maps/Test/NavMesh.asset", "Assets/AddressableResources/Maps/Test/NavMesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
			new AddressableConfig(131, "Maps/Test/ReflectionProbe-0.exr", "Assets/AddressableResources/Maps/Test/ReflectionProbe-0.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
			new AddressableConfig(132, "Maps/Test/ReflectionProbe-1.exr", "Assets/AddressableResources/Maps/Test/ReflectionProbe-1.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
			new AddressableConfig(133, "Maps/Test/SmallWilderness_NavMesh_data.asset", "Assets/AddressableResources/Maps/Test/SmallWilderness_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(134, "Maps/Test/TestScene.asset", "Assets/AddressableResources/Maps/Test/TestScene.asset", typeof(MapAsset), new [] {"GenerateIds"}),
			new AddressableConfig(135, "Maps/Test/TestScene_NavMesh.asset", "Assets/AddressableResources/Maps/Test/TestScene_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
			new AddressableConfig(136, "Maps/Test/TestScene_NavMesh_data.asset", "Assets/AddressableResources/Maps/Test/TestScene_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(137, "Maps/Test/TestScene_Scene.unity", "Assets/AddressableResources/Maps/Test/TestScene_Scene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
			new AddressableConfig(138, "Maps/Test/TestScene_mesh.asset", "Assets/AddressableResources/Maps/Test/TestScene_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(139, "Maps/District/District.asset", "Assets/AddressableResources/Maps/District/District.asset", typeof(MapAsset), new [] {"GenerateIds"}),
			new AddressableConfig(140, "Maps/District/DistrictScene.unity", "Assets/AddressableResources/Maps/District/DistrictScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
			new AddressableConfig(141, "Maps/District/District_LM0_final.hdr", "Assets/AddressableResources/Maps/District/District_LM0_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(142, "Maps/District/District_LMA1_final.hdr", "Assets/AddressableResources/Maps/District/District_LMA1_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(143, "Maps/District/District_LMA2_final.hdr", "Assets/AddressableResources/Maps/District/District_LMA2_final.hdr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(144, "Maps/District/District_NavMesh.asset", "Assets/AddressableResources/Maps/District/District_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
			new AddressableConfig(145, "Maps/District/District_NavMesh_data.asset", "Assets/AddressableResources/Maps/District/District_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(146, "Maps/District/District_mesh.asset", "Assets/AddressableResources/Maps/District/District_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(147, "Maps/District/LightingData.asset", "Assets/AddressableResources/Maps/District/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(148, "Maps/District/Lightmap-0_comp_dir.png", "Assets/AddressableResources/Maps/District/Lightmap-0_comp_dir.png", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(149, "Maps/District/Lightmap-0_comp_light.exr", "Assets/AddressableResources/Maps/District/Lightmap-0_comp_light.exr", typeof(UnityEngine.Texture2D), new [] {"GenerateIds"}),
			new AddressableConfig(150, "Maps/District/NavMesh-Navmesh.asset", "Assets/AddressableResources/Maps/District/NavMesh-Navmesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
			new AddressableConfig(151, "Maps/Battlelands/BattlelandsMap.asset", "Assets/AddressableResources/Maps/Battlelands/BattlelandsMap.asset", typeof(MapAsset), new [] {"GenerateIds"}),
			new AddressableConfig(152, "Maps/Battlelands/BattlelandsMapScene.unity", "Assets/AddressableResources/Maps/Battlelands/BattlelandsMapScene.unity", typeof(UnityEngine.SceneManagement.Scene), new [] {"GenerateIds"}),
			new AddressableConfig(153, "Maps/Battlelands/BattlelandsMap_NavMesh.asset", "Assets/AddressableResources/Maps/Battlelands/BattlelandsMap_NavMesh.asset", typeof(NavMeshAsset), new [] {"GenerateIds"}),
			new AddressableConfig(154, "Maps/Battlelands/BattlelandsMap_NavMesh_data.asset", "Assets/AddressableResources/Maps/Battlelands/BattlelandsMap_NavMesh_data.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(155, "Maps/Battlelands/BattlelandsMap_mesh.asset", "Assets/AddressableResources/Maps/Battlelands/BattlelandsMap_mesh.asset", typeof(BinaryDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(156, "Maps/Battlelands/LightingData.asset", "Assets/AddressableResources/Maps/Battlelands/LightingData.asset", typeof(UnityEditor.LightingDataAsset), new [] {"GenerateIds"}),
			new AddressableConfig(157, "Maps/Battlelands/NavMesh.asset", "Assets/AddressableResources/Maps/Battlelands/NavMesh.asset", typeof(UnityEngine.AI.NavMeshData), new [] {"GenerateIds"}),
			new AddressableConfig(158, "Maps/Battlelands/ReflectionProbe-0.exr", "Assets/AddressableResources/Maps/Battlelands/ReflectionProbe-0.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"}),
			new AddressableConfig(159, "Maps/Battlelands/ReflectionProbe-1.exr", "Assets/AddressableResources/Maps/Battlelands/ReflectionProbe-1.exr", typeof(UnityEngine.Cubemap), new [] {"GenerateIds"})
		}.AsReadOnly();
	}
}
