/* AUTO GENERATED CODE */

using System.Collections.Generic;
using System.Collections.ObjectModel;
using FirstLight.AddressablesExtensions;

// ReSharper disable InconsistentNaming
// ReSharper disable once CheckNamespace

namespace FirstLight.Game.Ids
{
	public enum AddressableId
	{
		Configs_AdjectiveDataConfigs,
		Configs_AdventureAssetConfigs,
		Configs_AudioAdventureAssetConfigs,
		Configs_AudioMainMenuAssetConfigs,
		Configs_AudioSharedAssetConfigs,
		Configs_BaseEquipmentStatsConfigs,
		Configs_BotConfigs,
		Configs_ChestConfigs,
		Configs_ConsumableConfigs,
		Configs_CustomAssetConfigs,
		Configs_DestructibleConfigs,
		Configs_DummyAssetConfigs,
		Configs_EditionDataConfigs,
		Configs_EquipmentStatsConfigs,
		Configs_FactionDataConfigs,
		Configs_GameConfigs,
		Configs_GradeDataConfigs,
		Configs_GraphicsConfig,
		Configs_IndicatorVfxAssetConfigs,
		Configs_MainMenuAssetConfigs,
		Configs_ManufacturerDataConfigs,
		Configs_MapConfigs,
		Configs_MapGridConfigs,
		Configs_MatchRewardConfigs,
		Configs_MaterialDataConfigs,
		Configs_MaterialVfxConfigs,
		Configs_PlayerLevelConfigs,
		Configs_PlayerRankAssetConfigs,
		Configs_QuantumPrototypeAssetConfigs,
		Configs_RarityDataConfigs,
		Configs_ResourcePoolConfigs,
		Configs_SceneAssetConfigs,
		Configs_ShrinkingCircleConfigs,
		Configs_SpecialConfigs,
		Configs_SpecialMoveAssetConfigs,
		Configs_SpriteAssetConfigs,
		Configs_VfxConfigs,
		Configs_VideoAssetConfigs,
		Configs_WeaponConfigs,
		Configs_Settings_AssetResources,
		Configs_Settings_Deterministic_Config,
		Configs_Settings_PhotonServerSettings,
		Configs_Settings_QuantumRunnerConfigs,
		Configs_Settings_SimulationConfig,
		Configs_Settings_UiConfigs,
		Video_AssaultRifle,
		Video_Intro,
		Video_SniperRifle,
		Video_SpecialAggroBeaconGrenade,
		Video_SpecialAimingAirstrike,
		Video_SpecialAimingStunGrenade,
		Video_SpecialAirstrikeSimple,
		Video_SpecialHealingField,
		Video_SpecialHealingMode,
		Video_SpecialInvisibilitySelf,
		Video_SpecialRageSelf,
		Video_SpecialShieldedCharge,
		Video_SpecialShieldSelf,
		Video_SpecialSkyLaserBeam,
		Timeline_FtueTimeline,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_CircleWipe,
		Assets_Art_SpriteAtlas_AdventureHud,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_DefaultIndicatorBase,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_LootIndicatorIcon,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_BossIndicatorOutside,
		Assets_Art_Textures_Ui_AdventureHud_HUDRankBackground,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_SpeedPill,
		Assets_Art_Textures_Ui_AdventureHud_Quests_QuestBarFill,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_PlayerIndicatorFace,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_MovementIndicatorStar,
		Assets_Art_Textures_Ui_AdventureControlsHud_Joystick_JoystickAutoAim,
		Assets_Art_Textures_Ui_AdventureControlsHud_Joystick_JoystickThumbRight,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_Female01Avatar,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_Male02Avatar,
		Assets_Art_Textures_Ui_AdventureHud_HUD_Coin,
		Assets_Art_Textures_Ui_AdventureWorldHud_HealthBar_HealthBarShine,
		Assets_Art_Textures_Ui_AdventureControlsHud_SpecialRing,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_WhiteRound,
		Assets_Art_Textures_Ui_AdventureHud_321Countdown_2Countdown,
		Assets_Art_Textures_Ui_AdventureControlsHud_Joystick_Joystick_Background,
		Assets_Art_Textures_Ui_AdventureHud_TimerBase,
		Assets_Art_Textures_Ui_AdventureHud_ReviveArrow,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_EnemyIndicatorBase,
		Assets_Art_Textures_Ui_AdventureHud_321Countdown_SmearSpecial,
		Assets_Art_Textures_Ui_AdventureHud_321Countdown_GOCountdown,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_PlayerIndicatorBase,
		Assets_Art_Textures_Ui_AdventureControlsHud_Joystick_JoystickManualAim,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_HealthPill,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_Armour,
		Assets_Art_Textures_Ui_AdventureHud_321Countdown_3Countdown,
		Assets_Art_Textures_Ui_AdventureHud_321Countdown_DiagonalWiper,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_Female02Avatar,
		Assets_Art_Textures_Ui_AdventureControlsHud_Joystick_JoystickThumbLeft,
		Assets_Art_Textures_Ui_AdventureHud_SkullKing,
		Assets_Art_Textures_Ui_AdventureControlsHud_SpecialButtonDirectional,
		Assets_Art_Textures_Ui_AdventureControlsHud_Joystick_Joystick_Handle_Aim,
		Assets_Art_Textures_Ui_AdventureControlsHud_Joystick_JoystickAutoAimBase,
		Assets_Art_Textures_Ui_AdventureHud_321Countdown_1Countdown,
		Assets_Art_Textures_Ui_AdventureHud_SkullKillCount,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_Male01Avatar,
		Assets_Art_Textures_Ui_AdventureHud_Quests_QuestBarQuestFill,
		Assets_Art_Textures_Ui_AdventureHud_BossArrow,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_EnemyRadialIndicator,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_LootIndicatorBase,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_PowerPill,
		Assets_Art_Textures_Ui_AdventureWorldHud_HealthBar_HealthBar,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_EnemyIndicatorFace,
		Assets_Art_Textures_Ui_AdventureHud_CheqFlag,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_BossIndicatorInside,
		Assets_Art_Textures_Ui_AdventureControlsHud_Joystick_Joystick_Handle_Move,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_PlayerAvatarKO,
		Assets_Art_Textures_Ui_AdventureHud_NearDeathVignette,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_RIP_Icon,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_PlayerAvatarGeneric,
		Assets_Art_Textures_Ui_AdventureHud_Quests_QuestTitleFrame,
		Assets_Art_Textures_Ui_AdventureHud_Quests_QuestBar,
		Assets_Art_Textures_Ui_AdventureControlsHud_SpecialButton,
		Assets_Art_Textures_Ui_AdventureHud_PlayerStatus_PlayerLeft,
		Assets_Art_Textures_Ui_AdventureWorldHud_Indicators_PlayerIndicatorFaceKO,
		Assets_Art_Textures_Ui_AdventureHud_HUD_AdventureCoin,
		Assets_Art_Prefabs_Particles_Dustclouds_M_DefaultDustCloud,
		Assets_Art_Textures_Particles_T_DustClouds,
		Assets_Art_Models_Items_M_Items,
		Assets_Art_Textures_Shared_T_ColorAtlas_C,
		Assets_Art_Textures_Shared_T_ColorAtlas_E,
		Assets_Art_Shaders_SG_CharacterShader,
		Assets_Art_Textures_Particles_Spark,
		Assets_Art_Shaders_SG_ParticleAdditiveHDR,
		Assets_Art_Materials_Particles_M_FireAndSmoke,
		Assets_Art_Materials_Particles_M_Beam,
		Assets_Art_Textures_Particles_T_SmokeAtlas_6x6,
		Assets_Art_Textures_Particles_VignetteMask,
		Assets_Art_Shaders_SG_Silhouette,
		Assets_Art_Models_Items_Lost_Items,
		Assets_Art_VFXGraphs_SpawnOrb,
		Assets_Art_Materials_PM_Environment,
		Assets_Art_Models_Environment_Props_Barrels,
		Assets_Art_Models_Environment_Props_T_DomesticJunk_C,
		Assets_Art_Animation_Humanoid_place,
		Assets_Art_Animation_Humanoid_idle02,
		Assets_Art_Animation_Humanoid_leap,
		Assets_Art_Animation_Humanoid_Inventory_Anims,
		Assets_Art_Animation_Humanoid_Humanoid_Anims,
		Assets_Art_Animation_Humanoid_death,
		Assets_Art_Models_Weapons_M_WeaponAtlas01,
		Assets_Art_Models_Weapons_Rifle_AK,
		Assets_Art_Models_Weapons_T_WeaponAtlas01_C,
		Assets_Art_Fonts_DynamicDuo_DynamicDuo_Heavy_Italic_SDF,
		DynamicDuo_Heavy_Italic_SDF_Outline_Plus_Drop_A,
		Assets_Art_Textures_Ui_SharedUI_ShadowFade,
		Assets_Libs_TextMesh_Pro_Fonts_LiberationSans,
		Assets_Art_Animation_UI_Buttons_DefaultButtonSelectPress2,
		Assets_Art_Fonts_DynamicDuo_DynamicDuo_Heavy_Italic_SDF_Outline_Plus_Drop_B,
		Assets_Art_Textures_Ui_LootScreen_LootSelectBButton,
		Assets_Art_SpriteAtlas_MainMenuHud,
		Assets_Art_Textures_Ui_Home_Screen_CrateIcon,
		Assets_Art_Textures_Ui_Home_Screen_IconHome,
		Assets_Art_Textures_Ui_LootScreen_WeaponNameBg,
		Assets_Art_Textures_Ui_EquipmentScreen_ItemCardEmpty,
		Assets_Art_Textures_Ui_LootScreen_EquipSlotEmpty,
		Assets_Art_Textures_Ui_TopBar_TopBarCell,
		Assets_Art_Textures_Ui_LootScreen_EquipSlotSelect2x,
		Assets_Art_Textures_Ui_TopBar_TopBarCellEnd,
		Assets_Art_Textures_Ui_EquipmentScreen_SortArrows,
		Assets_Art_Textures_Ui_Home_Screen_CharacterIcon,
		Assets_Art_Textures_Ui_Home_Screen_AreaButtonB,
		Assets_Art_Textures_Ui_TopBar_TopBarBase,
		Assets_Art_Textures_Ui_Home_Screen_TrophyBlank,
		Assets_Art_Textures_Ui_MainMenuHUD_MainMenuSelected,
		Assets_Art_Textures_Ui_LootScreen_BackButton,
		Assets_Art_Textures_Ui_Home_Screen_MapButton,
		Assets_Art_Textures_Ui_EquipmentScreen_EquipmentFrame,
		Assets_Art_Textures_Ui_EquipmentScreen_AimAutoIcon,
		Assets_Art_Textures_Ui_Home_Screen_CraftIcon,
		Assets_Art_Textures_Ui_Home_Screen_RewardShape,
		Assets_Art_Textures_Ui_LootScreen_EquipSlotEmpty2x,
		Assets_Art_Textures_Ui_EquipmentScreen_ItemCardeRare,
		Assets_Art_Textures_Ui_TopBar_TopBarEndReverse,
		Assets_Art_Textures_Ui_Home_Screen_HomeButton,
		Assets_Art_Textures_Ui_Buttons_BurgerButton_Blue,
		Assets_Art_Textures_Ui_Home_Screen_RewardsBase,
		Assets_Art_Textures_Ui_LootScreen_LootIconAmulet,
		Assets_Art_Textures_Ui_Home_Screen_SettingsCog,
		Assets_Art_Textures_Ui_LootScreen_GunItemIcon,
		Assets_Art_Textures_Ui_LootScreen_SmearNewWhite,
		Assets_Art_Textures_Ui_LootScreen_LootIconHeadgear,
		Assets_Art_Textures_Ui_TopBar_TopBarPlayerLevelBadge,
		Assets_Art_Textures_Ui_EquipmentScreen_AimManualIcon,
		Assets_Art_Textures_Ui_TopBar_TopBarCellFill,
		Assets_Art_Textures_Ui_LootScreen_LightRays,
		Assets_Art_Textures_Ui_Home_Screen_TrophyRoadHolder,
		Assets_Art_Textures_Ui_Buttons_CancelButton,
		Assets_Art_Textures_Ui_LootScreen_LootSelectAButton,
		Assets_Art_Textures_Ui_LootScreen_LootIconAll,
		Assets_Art_Textures_Ui_LootScreen_ShieldItemIcon,
		Assets_Art_Textures_Ui_Home_Screen_NameHolder,
		Assets_Art_Textures_Ui_LootScreen_LootIconShield,
		Assets_Art_Textures_Ui_Home_Screen_ShopIcon,
		Assets_Art_Textures_Ui_LootScreen_LootIconArmour,
		Assets_Art_Textures_Ui_Home_Screen_TrophyIcon,
		Assets_Art_Textures_Ui_Buttons_PopUp_Close,
		Assets_Art_Textures_Ui_Home_Screen_AreaButtonA,
		Assets_Art_Textures_Ui_EquipmentScreen_CardShine,
		Assets_Art_Textures_Ui_Home_Screen_TrophyRoadHolderNew,
		Assets_Art_Textures_Ui_LootScreen_LightRaysColor,
		Assets_Art_Textures_Ui_LootScreen_FootwearItemIcon,
		Assets_Art_Textures_Ui_LootScreen_ChacterAvatarIcon,
		Assets_Art_Textures_Ui_Home_Screen_RankBase,
		Assets_Art_Textures_Ui_EquipmentScreen_Group_28_2x,
		Assets_Art_Textures_Ui_EquipmentScreen_XP_Level_Icon,
		Assets_Art_Textures_Ui_LootScreen_GearBag,
		Assets_Art_Textures_Ui_Home_Screen_PlayButton,
		Assets_Art_Textures_Ui_Buttons_UnavailableButton,
		Assets_Art_Textures_Ui_Home_Screen_Settings,
		Assets_Art_Textures_Ui_Buttons_ToggleOff,
		Assets_Art_Textures_Ui_EquipmentScreen_MovieIconSmall,
		Assets_Art_Textures_Ui_LootScreen_ArmourItemIcon,
		Assets_Art_Textures_Ui_TopBar_TrophyRoadButton,
		Assets_Art_Textures_Ui_Home_Screen_SocialIcon,
		Assets_Art_Textures_Ui_Buttons_DiscordButton,
		Assets_Art_Textures_Ui_Home_Screen_EnhanceIcon,
		Assets_Art_Textures_Ui_LootScreen_BackHomeIcon,
		Assets_Art_Textures_Ui_LootScreen_BackIcon,
		Assets_Art_Textures_Ui_EquipmentScreen_EquipmentFrame_1,
		Assets_Art_Textures_Ui_Home_Screen_FuseIcon,
		Assets_Art_Textures_Ui_EquipmentScreen_EquipmentFrameA,
		Assets_Art_Textures_Ui_Buttons_GreenButton,
		Assets_Art_Textures_Ui_LootScreen_ChacterAvatarIcon2,
		Assets_Art_Textures_Ui_Notifications_NotificationUnique,
		Assets_Art_Textures_Ui_LootScreen_HeadgearItemIcon,
		Assets_Art_Textures_Ui_Home_Screen_RewardsSliderGraphic,
		Assets_Art_Textures_Ui_Home_Screen_SquadButton,
		Assets_Art_Textures_Ui_LootScreen_ItemCardLootSlot2,
		Assets_Art_Textures_Ui_Notifications_NotificationGroup,
		Assets_Art_Textures_Ui_EquipmentScreen_Weapon_AK,
		Assets_Art_Textures_Ui_Home_Screen_HomeButtonFlipped,
		Assets_Art_Textures_Ui_LootScreen_LootIconSkills,
		Assets_Art_Textures_Ui_EquipmentScreen_EquippedItem,
		Assets_Art_Textures_Ui_LootScreen_SmearNewShadow,
		Assets_Art_Textures_Ui_TopBar_TopBarEnd,
		Assets_Art_Textures_Ui_EquipmentScreen_Group_28,
		Assets_Art_Textures_Ui_LootScreen_Smear_Title_Black,
		Assets_Art_Textures_Ui_EquipmentScreen_ItemDecal,
		Assets_Art_Textures_Ui_Buttons_ToggleOn,
		Assets_Art_Textures_Ui_LootScreen_LootIconWeapon,
		Assets_Art_Textures_Ui_LootScreen_AmuletItemIcon,
		Assets_Art_Textures_Ui_TopBar_TopBarEnergy_Icon,
		Assets_Art_Textures_Ui_SharedUI_DefaultBase,
		Assets_Art_Timelines_UI_Signals_Director_Complete_Signal,
		Assets_Art_Animation_UI_GenericDialog_GenericDialog_Appear,
		Assets_Art_Animation_UI_GenericDialog_GenericDialog_Unpack,
		Assets_Art_Textures_Ui_SharedUI_DefaultArrowUp,
		Assets_Art_Fonts_JockeyOne_JockeyOne_Regular_SDF_InGame,
		Assets_Art_Materials_Particles_M_PickupSpot,
		Assets_Art_Models_Environment_Terrains_Arena_SkyBase01,
		Assets_Art_Models_Environment_BattleRoyalMaps_RoyaleMap01,
		Assets_AddressableResources_Fonts_LiberationSans_SDF,
		Assets_AddressableResources_Fonts_LiberationSans_SDF___Fallback,
		Assets_AddressableResources_TMP_Pro_Shaders_TMP_SDF,
		Assets_AddressableResources_TMP_Pro_Shaders_TMP_SDF_Mobile
	}

	public enum AddressableLabel
	{
		Label_Quantum
	}

	public static class AddressablePathLookup
	{
		public static readonly string AssetsAddressableResourcesTMPProShaders = "Assets/AddressableResources/TMP Pro/Shaders";
		public static readonly string AssetsAddressableResourcesFonts = "Assets/AddressableResources/Fonts";
		public static readonly string AssetsArtModelsEnvironmentBattleRoyalMaps = "Assets/Art/Models/Environment/BattleRoyalMaps";
		public static readonly string AssetsArtModelsEnvironmentTerrains = "Assets/Art/Models/Environment/Terrains";
		public static readonly string AssetsArtMaterialsParticles = "Assets/Art/Materials/Particles";
		public static readonly string AssetsArtFontsJockeyOne = "Assets/Art/Fonts/JockeyOne";
		public static readonly string AssetsArtTexturesUiSharedUI = "Assets/Art/Textures/Ui/SharedUI";
		public static readonly string AssetsArtAnimationUIGenericDialog = "Assets/Art/Animation/UI/GenericDialog";
		public static readonly string AssetsArtTimelinesUISignals = "Assets/Art/Timelines/UI/Signals";
		public static readonly string AssetsArtTexturesUiTopBar = "Assets/Art/Textures/Ui/TopBar";
		public static readonly string AssetsArtTexturesUiLootScreen = "Assets/Art/Textures/Ui/LootScreen";
		public static readonly string AssetsArtTexturesUiButtons = "Assets/Art/Textures/Ui/Buttons";
		public static readonly string AssetsArtTexturesUiEquipmentScreen = "Assets/Art/Textures/Ui/EquipmentScreen";
		public static readonly string AssetsArtTexturesUiHomeScreen = "Assets/Art/Textures/Ui/Home Screen";
		public static readonly string AssetsArtTexturesUiNotifications = "Assets/Art/Textures/Ui/Notifications";
		public static readonly string AssetsArtTexturesUiMainMenuHUD = "Assets/Art/Textures/Ui/MainMenuHUD";
		public static readonly string AssetsArtSpriteAtlas = "Assets/Art/SpriteAtlas";
		public static readonly string AssetsArtFontsDynamicDuo = "Assets/Art/Fonts/DynamicDuo";
		public static readonly string AssetsArtAnimationUIButtons = "Assets/Art/Animation/UI/Buttons";
		public static readonly string AssetsLibsTextMeshProFonts = "Assets/Libs/TextMesh Pro/Fonts";
		public static readonly string DynamicDuoHeavyItalicSDFOutlinePlusDropA = "DynamicDuo Heavy Italic SDF Outline Plus Drop A";
		public static readonly string AssetsArtModelsWeapons = "Assets/Art/Models/Weapons";
		public static readonly string AssetsArtAnimationHumanoid = "Assets/Art/Animation/Humanoid";
		public static readonly string AssetsArtModelsEnvironmentProps = "Assets/Art/Models/Environment/Props";
		public static readonly string AssetsArtMaterials = "Assets/Art/Materials";
		public static readonly string AssetsArtVFXGraphs = "Assets/Art/VFXGraphs";
		public static readonly string AssetsArtModelsItems = "Assets/Art/Models/Items";
		public static readonly string AssetsArtShaders = "Assets/Art/Shaders";
		public static readonly string AssetsArtTexturesParticles = "Assets/Art/Textures/Particles";
		public static readonly string AssetsArtTexturesShared = "Assets/Art/Textures/Shared";
		public static readonly string AssetsArtPrefabsParticlesDustclouds = "Assets/Art/Prefabs/Particles/Dustclouds";
		public static readonly string AssetsArtTexturesUiAdventureHud = "Assets/Art/Textures/Ui/AdventureHud";
		public static readonly string AssetsArtTexturesUiAdventureWorldHudIndicators = "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators";
		public static readonly string AssetsArtTexturesUiAdventureHudPlayerStatus = "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus";
		public static readonly string AssetsArtTexturesUiAdventureControlsHud = "Assets/Art/Textures/Ui/AdventureControlsHud";
		public static readonly string AssetsArtTexturesUiAdventureHudQuests = "Assets/Art/Textures/Ui/AdventureHud/Quests";
		public static readonly string AssetsArtTexturesUiAdventureControlsHudJoystick = "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick";
		public static readonly string AssetsArtTexturesUiAdventureWorldHudHealthBar = "Assets/Art/Textures/Ui/AdventureWorldHud/HealthBar";
		public static readonly string AssetsArtTexturesUiAdventureHud321Countdown = "Assets/Art/Textures/Ui/AdventureHud/321Countdown";
		public static readonly string Timeline = "Timeline";
		public static readonly string Video = "Video";
		public static readonly string ConfigsSettings = "Configs/Settings";
		public static readonly string Configs = "Configs";
	}

	public static class AddressableConfigLookup
	{
		public static IList<AddressableConfig> Configs => _addressableConfigs;
		public static IList<string> Labels => _addressableLabels;

		public static AddressableConfig GetConfig(this AddressableId addressable)
		{
			return _addressableConfigs[(int) addressable];
		}

		public static IList<AddressableConfig> GetConfigs(this AddressableLabel label)
		{
			return _addressableLabelMap[_addressableLabels[(int) label]];
		}

		public static IList<AddressableConfig> GetConfigs(string label)
		{
			return _addressableLabelMap[label];
		}

		public static string ToLabelString(this AddressableLabel label)
		{
			return _addressableLabels[(int) label];
		}

		private static readonly IList<string> _addressableLabels = new List<string>
		{
			"Quantum"
		}.AsReadOnly();

		private static readonly IReadOnlyDictionary<string, IList<AddressableConfig>> _addressableLabelMap = new ReadOnlyDictionary<string, IList<AddressableConfig>>(new Dictionary<string, IList<AddressableConfig>>
		{
			{"Quantum", new List<AddressableConfig>
				{
					new AddressableConfig(0, "QuantumAssets/Spawners/PlatformSpawner.prefab", "Assets/AddressableResources/QuantumAssets/Spawners/PlatformSpawner.prefab", typeof(UnityEngine.GameObject), new [] {"Quantum","Ignore"}),
					new AddressableConfig(1, "QuantumAssets/Spawners/LegacyWeaponPlatformSpawner.prefab", "Assets/AddressableResources/QuantumAssets/Spawners/LegacyWeaponPlatformSpawner.prefab", typeof(UnityEngine.GameObject), new [] {"Quantum","Ignore"}),
					new AddressableConfig(2, "QuantumAssets/Projectiles/PlayerBullet.prefab", "Assets/AddressableResources/QuantumAssets/Projectiles/PlayerBullet.prefab", typeof(UnityEngine.GameObject), new [] {"Quantum","Ignore"}),
					new AddressableConfig(3, "QuantumAssets/Physics Config Assets/Player CharacterController.asset", "Assets/AddressableResources/QuantumAssets/Physics Config Assets/Player CharacterController.asset", typeof(CharacterController3DConfigAsset), new [] {"Quantum","Ignore"}),
					new AddressableConfig(4, "QuantumAssets/Physics Config Assets/Bot NavMeshAgentConfig.asset", "Assets/AddressableResources/QuantumAssets/Physics Config Assets/Bot NavMeshAgentConfig.asset", typeof(NavMeshAgentConfigAsset), new [] {"Quantum","Ignore"}),
					new AddressableConfig(5, "QuantumAssets/Destructibles/Barrel.prefab", "Assets/AddressableResources/QuantumAssets/Destructibles/Barrel.prefab", typeof(UnityEngine.GameObject), new [] {"Quantum","Ignore"}),
					new AddressableConfig(6, "QuantumAssets/Default Config Assets/Default PhysicsMaterialAsset.asset", "Assets/AddressableResources/QuantumAssets/Default Config Assets/Default PhysicsMaterialAsset.asset", typeof(PhysicsMaterialAsset), new [] {"Quantum","Ignore"}),
					new AddressableConfig(7, "QuantumAssets/Default Config Assets/Default NavMeshAgentConfigAsset.asset", "Assets/AddressableResources/QuantumAssets/Default Config Assets/Default NavMeshAgentConfigAsset.asset", typeof(NavMeshAgentConfigAsset), new [] {"Quantum","Ignore"}),
					new AddressableConfig(8, "QuantumAssets/Default Config Assets/Default CharacterController3DConfigAsset.asset", "Assets/AddressableResources/QuantumAssets/Default Config Assets/Default CharacterController3DConfigAsset.asset", typeof(CharacterController3DConfigAsset), new [] {"Quantum","Ignore"}),
					new AddressableConfig(9, "QuantumAssets/Default Config Assets/Default CharacterController2DConfigAsset.asset", "Assets/AddressableResources/QuantumAssets/Default Config Assets/Default CharacterController2DConfigAsset.asset", typeof(CharacterController2DConfigAsset), new [] {"Quantum","Ignore"}),
					new AddressableConfig(10, "QuantumAssets/Collectables/EquipmentPickup.prefab", "Assets/AddressableResources/QuantumAssets/Collectables/EquipmentPickup.prefab", typeof(UnityEngine.GameObject), new [] {"Quantum","Ignore"}),
					new AddressableConfig(11, "QuantumAssets/Collectables/ConsumablePickup.prefab", "Assets/AddressableResources/QuantumAssets/Collectables/ConsumablePickup.prefab", typeof(UnityEngine.GameObject), new [] {"Quantum","Ignore"}),
					new AddressableConfig(12, "QuantumAssets/Collectables/ChestPickup.prefab", "Assets/AddressableResources/QuantumAssets/Collectables/ChestPickup.prefab", typeof(UnityEngine.GameObject), new [] {"Quantum","Ignore"}),
					new AddressableConfig(13, "QuantumAssets/CircuitExport/HFSM_Assets/Player.asset", "Assets/AddressableResources/QuantumAssets/CircuitExport/HFSM_Assets/Player.asset", typeof(HFSMRootAsset), new [] {"Quantum","Ignore"}),
					new AddressableConfig(14, "QuantumAssets/CircuitExport/Blackboard_Assets/PlayerBlackboardInitializer.asset", "Assets/AddressableResources/QuantumAssets/CircuitExport/Blackboard_Assets/PlayerBlackboardInitializer.asset", typeof(AIBlackboardInitializerAsset), new [] {"Quantum","Ignore"}),
					new AddressableConfig(15, "QuantumAssets/CircuitExport/Blackboard_Assets/PlayerBlackboard.asset", "Assets/AddressableResources/QuantumAssets/CircuitExport/Blackboard_Assets/PlayerBlackboard.asset", typeof(AIBlackboardAsset), new [] {"Quantum","Ignore"}),
					new AddressableConfig(16, "QuantumAssets/Characters/PlayerCharacter.prefab", "Assets/AddressableResources/QuantumAssets/Characters/PlayerCharacter.prefab", typeof(UnityEngine.GameObject), new [] {"Quantum","Ignore"}),
					new AddressableConfig(17, "QuantumAssets/Characters/DummyCharacter.prefab", "Assets/AddressableResources/QuantumAssets/Characters/DummyCharacter.prefab", typeof(UnityEngine.GameObject), new [] {"Quantum","Ignore"}),
					new AddressableConfig(18, "Configs/Settings/UiConfigs.asset", "Assets/AddressableResources/Configs/Settings/UiConfigs.asset", typeof(FirstLight.UiService.UiConfigs), new [] {"Quantum"}),
					new AddressableConfig(19, "Configs/Settings/SimulationConfig.asset", "Assets/AddressableResources/Configs/Settings/SimulationConfig.asset", typeof(SimulationConfigAsset), new [] {"Quantum"}),
					new AddressableConfig(20, "Configs/Settings/QuantumRunnerConfigs.asset", "Assets/AddressableResources/Configs/Settings/QuantumRunnerConfigs.asset", typeof(FirstLight.Game.Configs.QuantumRunnerConfigs), new [] {"Quantum"}),
					new AddressableConfig(21, "Configs/Settings/PhotonServerSettings.asset", "Assets/AddressableResources/Configs/Settings/PhotonServerSettings.asset", typeof(PhotonServerSettings), new [] {"Quantum"}),
					new AddressableConfig(22, "Configs/Settings/Deterministic Config.asset", "Assets/AddressableResources/Configs/Settings/Deterministic Config.asset", typeof(DeterministicSessionConfigAsset), new [] {"Quantum"}),
					new AddressableConfig(23, "Configs/Settings/AssetResources.asset", "Assets/AddressableResources/Configs/Settings/AssetResources.asset", typeof(Quantum.AssetResourceContainer), new [] {"Quantum"}),
					new AddressableConfig(24, "Configs/WeaponConfigs.asset", "Assets/AddressableResources/Configs/WeaponConfigs.asset", typeof(FirstLight.Game.Configs.WeaponConfigs), new [] {"Quantum"}),
					new AddressableConfig(25, "Configs/VideoAssetConfigs.asset", "Assets/AddressableResources/Configs/VideoAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.VideoAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(26, "Configs/VfxConfigs.asset", "Assets/AddressableResources/Configs/VfxConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.VfxAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(27, "Configs/SpriteAssetConfigs.asset", "Assets/AddressableResources/Configs/SpriteAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SpriteAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(28, "Configs/SpecialMoveAssetConfigs.asset", "Assets/AddressableResources/Configs/SpecialMoveAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SpecialMoveAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(29, "Configs/SpecialConfigs.asset", "Assets/AddressableResources/Configs/SpecialConfigs.asset", typeof(FirstLight.Game.Configs.SpecialConfigs), new [] {"Quantum"}),
					new AddressableConfig(30, "Configs/ShrinkingCircleConfigs.asset", "Assets/AddressableResources/Configs/ShrinkingCircleConfigs.asset", typeof(FirstLight.Game.Configs.ShrinkingCircleConfigs), new [] {"Quantum"}),
					new AddressableConfig(31, "Configs/SceneAssetConfigs.asset", "Assets/AddressableResources/Configs/SceneAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SceneAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(32, "Configs/ResourcePoolConfigs.asset", "Assets/AddressableResources/Configs/ResourcePoolConfigs.asset", typeof(FirstLight.Game.Configs.ResourcePoolConfigs), new [] {"Quantum"}),
					new AddressableConfig(33, "Configs/RarityDataConfigs.asset", "Assets/AddressableResources/Configs/RarityDataConfigs.asset", typeof(FirstLight.Game.Configs.RarityDataConfigs), new [] {"Quantum"}),
					new AddressableConfig(34, "Configs/QuantumPrototypeAssetConfigs.asset", "Assets/AddressableResources/Configs/QuantumPrototypeAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.QuantumPrototypeAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(35, "Configs/PlayerRankAssetConfigs.asset", "Assets/AddressableResources/Configs/PlayerRankAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.PlayerRankAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(36, "Configs/PlayerLevelConfigs.asset", "Assets/AddressableResources/Configs/PlayerLevelConfigs.asset", typeof(FirstLight.Game.Configs.PlayerLevelConfigs), new [] {"Quantum"}),
					new AddressableConfig(37, "Configs/MaterialVfxConfigs.asset", "Assets/AddressableResources/Configs/MaterialVfxConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.MaterialVfxConfigs), new [] {"Quantum"}),
					new AddressableConfig(38, "Configs/MaterialDataConfigs.asset", "Assets/AddressableResources/Configs/MaterialDataConfigs.asset", typeof(FirstLight.Game.Configs.MaterialDataConfigs), new [] {"Quantum"}),
					new AddressableConfig(39, "Configs/MatchRewardConfigs.asset", "Assets/AddressableResources/Configs/MatchRewardConfigs.asset", typeof(FirstLight.Game.Configs.MatchRewardConfigs), new [] {"Quantum"}),
					new AddressableConfig(40, "Configs/MapGridConfigs.asset", "Assets/AddressableResources/Configs/MapGridConfigs.asset", typeof(FirstLight.Game.Configs.MapGridConfigs), new [] {"Quantum"}),
					new AddressableConfig(41, "Configs/MapConfigs.asset", "Assets/AddressableResources/Configs/MapConfigs.asset", typeof(FirstLight.Game.Configs.MapConfigs), new [] {"Quantum"}),
					new AddressableConfig(42, "Configs/ManufacturerDataConfigs.asset", "Assets/AddressableResources/Configs/ManufacturerDataConfigs.asset", typeof(FirstLight.Game.Configs.ManufacturerDataConfigs), new [] {"Quantum"}),
					new AddressableConfig(43, "Configs/MainMenuAssetConfigs.asset", "Assets/AddressableResources/Configs/MainMenuAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.MainMenuAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(44, "Configs/IndicatorVfxAssetConfigs.asset", "Assets/AddressableResources/Configs/IndicatorVfxAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.IndicatorVfxAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(45, "Configs/GraphicsConfig.asset", "Assets/AddressableResources/Configs/GraphicsConfig.asset", typeof(FirstLight.Game.Configs.GraphicsConfig), new [] {"Quantum"}),
					new AddressableConfig(46, "Configs/GradeDataConfigs.asset", "Assets/AddressableResources/Configs/GradeDataConfigs.asset", typeof(FirstLight.Game.Configs.GradeDataConfigs), new [] {"Quantum"}),
					new AddressableConfig(47, "Configs/GameConfigs.asset", "Assets/AddressableResources/Configs/GameConfigs.asset", typeof(FirstLight.Game.Configs.GameConfigs), new [] {"Quantum"}),
					new AddressableConfig(48, "Configs/FactionDataConfigs.asset", "Assets/AddressableResources/Configs/FactionDataConfigs.asset", typeof(FirstLight.Game.Configs.FactionDataConfigs), new [] {"Quantum"}),
					new AddressableConfig(49, "Configs/EquipmentStatsConfigs.asset", "Assets/AddressableResources/Configs/EquipmentStatsConfigs.asset", typeof(FirstLight.Game.Configs.EquipmentStatsConfigs), new [] {"Quantum"}),
					new AddressableConfig(50, "Configs/EditionDataConfigs.asset", "Assets/AddressableResources/Configs/EditionDataConfigs.asset", typeof(FirstLight.Game.Configs.EditionDataConfigs), new [] {"Quantum"}),
					new AddressableConfig(51, "Configs/DummyAssetConfigs.asset", "Assets/AddressableResources/Configs/DummyAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.DummyAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(52, "Configs/DestructibleConfigs.asset", "Assets/AddressableResources/Configs/DestructibleConfigs.asset", typeof(FirstLight.Game.Configs.DestructibleConfigs), new [] {"Quantum"}),
					new AddressableConfig(53, "Configs/CustomAssetConfigs.asset", "Assets/AddressableResources/Configs/CustomAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.CustomAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(54, "Configs/ConsumableConfigs.asset", "Assets/AddressableResources/Configs/ConsumableConfigs.asset", typeof(FirstLight.Game.Configs.ConsumableConfigs), new [] {"Quantum"}),
					new AddressableConfig(55, "Configs/ChestConfigs.asset", "Assets/AddressableResources/Configs/ChestConfigs.asset", typeof(FirstLight.Game.Configs.ChestConfigs), new [] {"Quantum"}),
					new AddressableConfig(56, "Configs/BotConfigs.asset", "Assets/AddressableResources/Configs/BotConfigs.asset", typeof(FirstLight.Game.Configs.BotConfigs), new [] {"Quantum"}),
					new AddressableConfig(57, "Configs/BaseEquipmentStatsConfigs.asset", "Assets/AddressableResources/Configs/BaseEquipmentStatsConfigs.asset", typeof(FirstLight.Game.Configs.BaseEquipmentStatsConfigs), new [] {"Quantum"}),
					new AddressableConfig(58, "Configs/AudioSharedAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioSharedAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioSharedAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(59, "Configs/AudioMainMenuAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioMainMenuAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioMainMenuAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(60, "Configs/AudioAdventureAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioAdventureAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioAdventureAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(61, "Configs/AdventureAssetConfigs.asset", "Assets/AddressableResources/Configs/AdventureAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AdventureAssetConfigs), new [] {"Quantum"}),
					new AddressableConfig(62, "Configs/AdjectiveDataConfigs.asset", "Assets/AddressableResources/Configs/AdjectiveDataConfigs.asset", typeof(FirstLight.Game.Configs.AdjectiveDataConfigs), new [] {"Quantum"}),
				}.AsReadOnly()}
		});

		private static readonly IList<AddressableConfig> _addressableConfigs = new List<AddressableConfig>
		{
			new AddressableConfig(0, "Configs/AdjectiveDataConfigs.asset", "Assets/AddressableResources/Configs/AdjectiveDataConfigs.asset", typeof(FirstLight.Game.Configs.AdjectiveDataConfigs), new [] {"Quantum"}),
			new AddressableConfig(1, "Configs/AdventureAssetConfigs.asset", "Assets/AddressableResources/Configs/AdventureAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AdventureAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(2, "Configs/AudioAdventureAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioAdventureAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioAdventureAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(3, "Configs/AudioMainMenuAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioMainMenuAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioMainMenuAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(4, "Configs/AudioSharedAssetConfigs.asset", "Assets/AddressableResources/Configs/AudioSharedAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.AudioSharedAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(5, "Configs/BaseEquipmentStatsConfigs.asset", "Assets/AddressableResources/Configs/BaseEquipmentStatsConfigs.asset", typeof(FirstLight.Game.Configs.BaseEquipmentStatsConfigs), new [] {"Quantum"}),
			new AddressableConfig(6, "Configs/BotConfigs.asset", "Assets/AddressableResources/Configs/BotConfigs.asset", typeof(FirstLight.Game.Configs.BotConfigs), new [] {"Quantum"}),
			new AddressableConfig(7, "Configs/ChestConfigs.asset", "Assets/AddressableResources/Configs/ChestConfigs.asset", typeof(FirstLight.Game.Configs.ChestConfigs), new [] {"Quantum"}),
			new AddressableConfig(8, "Configs/ConsumableConfigs.asset", "Assets/AddressableResources/Configs/ConsumableConfigs.asset", typeof(FirstLight.Game.Configs.ConsumableConfigs), new [] {"Quantum"}),
			new AddressableConfig(9, "Configs/CustomAssetConfigs.asset", "Assets/AddressableResources/Configs/CustomAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.CustomAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(10, "Configs/DestructibleConfigs.asset", "Assets/AddressableResources/Configs/DestructibleConfigs.asset", typeof(FirstLight.Game.Configs.DestructibleConfigs), new [] {"Quantum"}),
			new AddressableConfig(11, "Configs/DummyAssetConfigs.asset", "Assets/AddressableResources/Configs/DummyAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.DummyAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(12, "Configs/EditionDataConfigs.asset", "Assets/AddressableResources/Configs/EditionDataConfigs.asset", typeof(FirstLight.Game.Configs.EditionDataConfigs), new [] {"Quantum"}),
			new AddressableConfig(13, "Configs/EquipmentStatsConfigs.asset", "Assets/AddressableResources/Configs/EquipmentStatsConfigs.asset", typeof(FirstLight.Game.Configs.EquipmentStatsConfigs), new [] {"Quantum"}),
			new AddressableConfig(14, "Configs/FactionDataConfigs.asset", "Assets/AddressableResources/Configs/FactionDataConfigs.asset", typeof(FirstLight.Game.Configs.FactionDataConfigs), new [] {"Quantum"}),
			new AddressableConfig(15, "Configs/GameConfigs.asset", "Assets/AddressableResources/Configs/GameConfigs.asset", typeof(FirstLight.Game.Configs.GameConfigs), new [] {"Quantum"}),
			new AddressableConfig(16, "Configs/GradeDataConfigs.asset", "Assets/AddressableResources/Configs/GradeDataConfigs.asset", typeof(FirstLight.Game.Configs.GradeDataConfigs), new [] {"Quantum"}),
			new AddressableConfig(17, "Configs/GraphicsConfig.asset", "Assets/AddressableResources/Configs/GraphicsConfig.asset", typeof(FirstLight.Game.Configs.GraphicsConfig), new [] {"Quantum"}),
			new AddressableConfig(18, "Configs/IndicatorVfxAssetConfigs.asset", "Assets/AddressableResources/Configs/IndicatorVfxAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.IndicatorVfxAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(19, "Configs/MainMenuAssetConfigs.asset", "Assets/AddressableResources/Configs/MainMenuAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.MainMenuAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(20, "Configs/ManufacturerDataConfigs.asset", "Assets/AddressableResources/Configs/ManufacturerDataConfigs.asset", typeof(FirstLight.Game.Configs.ManufacturerDataConfigs), new [] {"Quantum"}),
			new AddressableConfig(21, "Configs/MapConfigs.asset", "Assets/AddressableResources/Configs/MapConfigs.asset", typeof(FirstLight.Game.Configs.MapConfigs), new [] {"Quantum"}),
			new AddressableConfig(22, "Configs/MapGridConfigs.asset", "Assets/AddressableResources/Configs/MapGridConfigs.asset", typeof(FirstLight.Game.Configs.MapGridConfigs), new [] {"Quantum"}),
			new AddressableConfig(23, "Configs/MatchRewardConfigs.asset", "Assets/AddressableResources/Configs/MatchRewardConfigs.asset", typeof(FirstLight.Game.Configs.MatchRewardConfigs), new [] {"Quantum"}),
			new AddressableConfig(24, "Configs/MaterialDataConfigs.asset", "Assets/AddressableResources/Configs/MaterialDataConfigs.asset", typeof(FirstLight.Game.Configs.MaterialDataConfigs), new [] {"Quantum"}),
			new AddressableConfig(25, "Configs/MaterialVfxConfigs.asset", "Assets/AddressableResources/Configs/MaterialVfxConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.MaterialVfxConfigs), new [] {"Quantum"}),
			new AddressableConfig(26, "Configs/PlayerLevelConfigs.asset", "Assets/AddressableResources/Configs/PlayerLevelConfigs.asset", typeof(FirstLight.Game.Configs.PlayerLevelConfigs), new [] {"Quantum"}),
			new AddressableConfig(27, "Configs/PlayerRankAssetConfigs.asset", "Assets/AddressableResources/Configs/PlayerRankAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.PlayerRankAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(28, "Configs/QuantumPrototypeAssetConfigs.asset", "Assets/AddressableResources/Configs/QuantumPrototypeAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.QuantumPrototypeAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(29, "Configs/RarityDataConfigs.asset", "Assets/AddressableResources/Configs/RarityDataConfigs.asset", typeof(FirstLight.Game.Configs.RarityDataConfigs), new [] {"Quantum"}),
			new AddressableConfig(30, "Configs/ResourcePoolConfigs.asset", "Assets/AddressableResources/Configs/ResourcePoolConfigs.asset", typeof(FirstLight.Game.Configs.ResourcePoolConfigs), new [] {"Quantum"}),
			new AddressableConfig(31, "Configs/SceneAssetConfigs.asset", "Assets/AddressableResources/Configs/SceneAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SceneAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(32, "Configs/ShrinkingCircleConfigs.asset", "Assets/AddressableResources/Configs/ShrinkingCircleConfigs.asset", typeof(FirstLight.Game.Configs.ShrinkingCircleConfigs), new [] {"Quantum"}),
			new AddressableConfig(33, "Configs/SpecialConfigs.asset", "Assets/AddressableResources/Configs/SpecialConfigs.asset", typeof(FirstLight.Game.Configs.SpecialConfigs), new [] {"Quantum"}),
			new AddressableConfig(34, "Configs/SpecialMoveAssetConfigs.asset", "Assets/AddressableResources/Configs/SpecialMoveAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SpecialMoveAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(35, "Configs/SpriteAssetConfigs.asset", "Assets/AddressableResources/Configs/SpriteAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.SpriteAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(36, "Configs/VfxConfigs.asset", "Assets/AddressableResources/Configs/VfxConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.VfxAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(37, "Configs/VideoAssetConfigs.asset", "Assets/AddressableResources/Configs/VideoAssetConfigs.asset", typeof(FirstLight.Game.Configs.AssetConfigs.VideoAssetConfigs), new [] {"Quantum"}),
			new AddressableConfig(38, "Configs/WeaponConfigs.asset", "Assets/AddressableResources/Configs/WeaponConfigs.asset", typeof(FirstLight.Game.Configs.WeaponConfigs), new [] {"Quantum"}),
			new AddressableConfig(39, "Configs/Settings/AssetResources.asset", "Assets/AddressableResources/Configs/Settings/AssetResources.asset", typeof(Quantum.AssetResourceContainer), new [] {"Quantum"}),
			new AddressableConfig(40, "Configs/Settings/Deterministic Config.asset", "Assets/AddressableResources/Configs/Settings/Deterministic Config.asset", typeof(DeterministicSessionConfigAsset), new [] {"Quantum"}),
			new AddressableConfig(41, "Configs/Settings/PhotonServerSettings.asset", "Assets/AddressableResources/Configs/Settings/PhotonServerSettings.asset", typeof(PhotonServerSettings), new [] {"Quantum"}),
			new AddressableConfig(42, "Configs/Settings/QuantumRunnerConfigs.asset", "Assets/AddressableResources/Configs/Settings/QuantumRunnerConfigs.asset", typeof(FirstLight.Game.Configs.QuantumRunnerConfigs), new [] {"Quantum"}),
			new AddressableConfig(43, "Configs/Settings/SimulationConfig.asset", "Assets/AddressableResources/Configs/Settings/SimulationConfig.asset", typeof(SimulationConfigAsset), new [] {"Quantum"}),
			new AddressableConfig(44, "Configs/Settings/UiConfigs.asset", "Assets/AddressableResources/Configs/Settings/UiConfigs.asset", typeof(FirstLight.UiService.UiConfigs), new [] {"Quantum"}),
			new AddressableConfig(45, "Video/AssaultRifle.mp4", "Assets/AddressableResources/Video/AssaultRifle.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(46, "Video/Intro.mp4", "Assets/AddressableResources/Video/Intro.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(47, "Video/SniperRifle.mp4", "Assets/AddressableResources/Video/SniperRifle.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(48, "Video/SpecialAggroBeaconGrenade.mp4", "Assets/AddressableResources/Video/SpecialAggroBeaconGrenade.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(49, "Video/SpecialAimingAirstrike.mp4", "Assets/AddressableResources/Video/SpecialAimingAirstrike.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(50, "Video/SpecialAimingStunGrenade.mp4", "Assets/AddressableResources/Video/SpecialAimingStunGrenade.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(51, "Video/SpecialAirstrikeSimple.mp4", "Assets/AddressableResources/Video/SpecialAirstrikeSimple.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(52, "Video/SpecialHealingField.mp4", "Assets/AddressableResources/Video/SpecialHealingField.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(53, "Video/SpecialHealingMode.mp4", "Assets/AddressableResources/Video/SpecialHealingMode.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(54, "Video/SpecialInvisibilitySelf.mp4", "Assets/AddressableResources/Video/SpecialInvisibilitySelf.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(55, "Video/SpecialRageSelf.mp4", "Assets/AddressableResources/Video/SpecialRageSelf.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(56, "Video/SpecialShieldedCharge.mp4", "Assets/AddressableResources/Video/SpecialShieldedCharge.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(57, "Video/SpecialShieldSelf.mp4", "Assets/AddressableResources/Video/SpecialShieldSelf.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(58, "Video/SpecialSkyLaserBeam.mp4", "Assets/AddressableResources/Video/SpecialSkyLaserBeam.mp4", typeof(UnityEngine.Video.VideoClip), new [] {""}),
			new AddressableConfig(59, "Timeline/FtueTimeline.prefab", "Assets/AddressableResources/Timeline/FtueTimeline.prefab", typeof(UnityEngine.GameObject), new [] {""}),
			new AddressableConfig(60, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/CircleWipe.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/CircleWipe.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(61, "Assets/Art/SpriteAtlas/AdventureHud.spriteatlas", "Assets/Art/SpriteAtlas/AdventureHud.spriteatlas", typeof(UnityEngine.U2D.SpriteAtlas), new [] {""}),
			new AddressableConfig(62, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/DefaultIndicatorBase.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/DefaultIndicatorBase.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(63, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/LootIndicatorIcon.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/LootIndicatorIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(64, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/BossIndicatorOutside.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/BossIndicatorOutside.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(65, "Assets/Art/Textures/Ui/AdventureHud/HUDRankBackground.png", "Assets/Art/Textures/Ui/AdventureHud/HUDRankBackground.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(66, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/SpeedPill.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/SpeedPill.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(67, "Assets/Art/Textures/Ui/AdventureHud/Quests/QuestBarFill.png", "Assets/Art/Textures/Ui/AdventureHud/Quests/QuestBarFill.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(68, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/PlayerIndicatorFace.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/PlayerIndicatorFace.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(69, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/MovementIndicatorStar.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/MovementIndicatorStar.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(70, "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/JoystickAutoAim.png", "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/JoystickAutoAim.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(71, "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/JoystickThumbRight.png", "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/JoystickThumbRight.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(72, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/Female01Avatar.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/Female01Avatar.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(73, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/Male02Avatar.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/Male02Avatar.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(74, "Assets/Art/Textures/Ui/AdventureHud/HUD_Coin.png", "Assets/Art/Textures/Ui/AdventureHud/HUD_Coin.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(75, "Assets/Art/Textures/Ui/AdventureWorldHud/HealthBar/HealthBarShine.png", "Assets/Art/Textures/Ui/AdventureWorldHud/HealthBar/HealthBarShine.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(76, "Assets/Art/Textures/Ui/AdventureControlsHud/SpecialRing.png", "Assets/Art/Textures/Ui/AdventureControlsHud/SpecialRing.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(77, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/WhiteRound.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/WhiteRound.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(78, "Assets/Art/Textures/Ui/AdventureHud/321Countdown/2Countdown.png", "Assets/Art/Textures/Ui/AdventureHud/321Countdown/2Countdown.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(79, "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/Joystick_Background.png", "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/Joystick_Background.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(80, "Assets/Art/Textures/Ui/AdventureHud/TimerBase.png", "Assets/Art/Textures/Ui/AdventureHud/TimerBase.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(81, "Assets/Art/Textures/Ui/AdventureHud/ReviveArrow.png", "Assets/Art/Textures/Ui/AdventureHud/ReviveArrow.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(82, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/EnemyIndicatorBase.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/EnemyIndicatorBase.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(83, "Assets/Art/Textures/Ui/AdventureHud/321Countdown/SmearSpecial.png", "Assets/Art/Textures/Ui/AdventureHud/321Countdown/SmearSpecial.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(84, "Assets/Art/Textures/Ui/AdventureHud/321Countdown/GOCountdown.png", "Assets/Art/Textures/Ui/AdventureHud/321Countdown/GOCountdown.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(85, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/PlayerIndicatorBase.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/PlayerIndicatorBase.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(86, "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/JoystickManualAim.png", "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/JoystickManualAim.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(87, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/HealthPill.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/HealthPill.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(88, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/Armour.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/Armour.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(89, "Assets/Art/Textures/Ui/AdventureHud/321Countdown/3Countdown.png", "Assets/Art/Textures/Ui/AdventureHud/321Countdown/3Countdown.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(90, "Assets/Art/Textures/Ui/AdventureHud/321Countdown/DiagonalWiper.png", "Assets/Art/Textures/Ui/AdventureHud/321Countdown/DiagonalWiper.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(91, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/Female02Avatar.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/Female02Avatar.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(92, "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/JoystickThumbLeft.png", "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/JoystickThumbLeft.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(93, "Assets/Art/Textures/Ui/AdventureHud/SkullKing.png", "Assets/Art/Textures/Ui/AdventureHud/SkullKing.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(94, "Assets/Art/Textures/Ui/AdventureControlsHud/SpecialButtonDirectional.png", "Assets/Art/Textures/Ui/AdventureControlsHud/SpecialButtonDirectional.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(95, "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/Joystick_Handle_Aim.png", "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/Joystick_Handle_Aim.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(96, "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/JoystickAutoAimBase.png", "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/JoystickAutoAimBase.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(97, "Assets/Art/Textures/Ui/AdventureHud/321Countdown/1Countdown.png", "Assets/Art/Textures/Ui/AdventureHud/321Countdown/1Countdown.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(98, "Assets/Art/Textures/Ui/AdventureHud/SkullKillCount.png", "Assets/Art/Textures/Ui/AdventureHud/SkullKillCount.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(99, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/Male01Avatar.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/Male01Avatar.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(100, "Assets/Art/Textures/Ui/AdventureHud/Quests/QuestBarQuestFill.png", "Assets/Art/Textures/Ui/AdventureHud/Quests/QuestBarQuestFill.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(101, "Assets/Art/Textures/Ui/AdventureHud/BossArrow.png", "Assets/Art/Textures/Ui/AdventureHud/BossArrow.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(102, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/EnemyRadialIndicator.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/EnemyRadialIndicator.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(103, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/LootIndicatorBase.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/LootIndicatorBase.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(104, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/PowerPill.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/PowerPill.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(105, "Assets/Art/Textures/Ui/AdventureWorldHud/HealthBar/HealthBar.png", "Assets/Art/Textures/Ui/AdventureWorldHud/HealthBar/HealthBar.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(106, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/EnemyIndicatorFace.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/EnemyIndicatorFace.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(107, "Assets/Art/Textures/Ui/AdventureHud/CheqFlag.png", "Assets/Art/Textures/Ui/AdventureHud/CheqFlag.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(108, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/BossIndicatorInside.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/BossIndicatorInside.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(109, "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/Joystick_Handle_Move.png", "Assets/Art/Textures/Ui/AdventureControlsHud/Joystick/Joystick_Handle_Move.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(110, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/PlayerAvatarKO.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/PlayerAvatarKO.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(111, "Assets/Art/Textures/Ui/AdventureHud/NearDeathVignette.png", "Assets/Art/Textures/Ui/AdventureHud/NearDeathVignette.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(112, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/RIP_Icon.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/RIP_Icon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(113, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/PlayerAvatarGeneric.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/PlayerAvatarGeneric.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(114, "Assets/Art/Textures/Ui/AdventureHud/Quests/QuestTitleFrame.png", "Assets/Art/Textures/Ui/AdventureHud/Quests/QuestTitleFrame.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(115, "Assets/Art/Textures/Ui/AdventureHud/Quests/QuestBar.png", "Assets/Art/Textures/Ui/AdventureHud/Quests/QuestBar.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(116, "Assets/Art/Textures/Ui/AdventureControlsHud/SpecialButton.png", "Assets/Art/Textures/Ui/AdventureControlsHud/SpecialButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(117, "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/PlayerLeft.png", "Assets/Art/Textures/Ui/AdventureHud/PlayerStatus/PlayerLeft.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(118, "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/PlayerIndicatorFaceKO.png", "Assets/Art/Textures/Ui/AdventureWorldHud/Indicators/PlayerIndicatorFaceKO.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(119, "Assets/Art/Textures/Ui/AdventureHud/HUD_AdventureCoin.png", "Assets/Art/Textures/Ui/AdventureHud/HUD_AdventureCoin.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(120, "Assets/Art/Prefabs/Particles/Dustclouds/M_DefaultDustCloud.mat", "Assets/Art/Prefabs/Particles/Dustclouds/M_DefaultDustCloud.mat", typeof(UnityEngine.Material), new [] {""}),
			new AddressableConfig(121, "Assets/Art/Textures/Particles/T_DustClouds.png", "Assets/Art/Textures/Particles/T_DustClouds.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(122, "Assets/Art/Models/Items/M_Items.mat", "Assets/Art/Models/Items/M_Items.mat", typeof(UnityEngine.Material), new [] {""}),
			new AddressableConfig(123, "Assets/Art/Textures/Shared/T_ColorAtlas_C.tga", "Assets/Art/Textures/Shared/T_ColorAtlas_C.tga", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(124, "Assets/Art/Textures/Shared/T_ColorAtlas_E.tga", "Assets/Art/Textures/Shared/T_ColorAtlas_E.tga", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(125, "Assets/Art/Shaders/SG_CharacterShader.shadergraph", "Assets/Art/Shaders/SG_CharacterShader.shadergraph", typeof(UnityEngine.Shader), new [] {""}),
			new AddressableConfig(126, "Assets/Art/Textures/Particles/Spark.png", "Assets/Art/Textures/Particles/Spark.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(127, "Assets/Art/Shaders/SG_ParticleAdditiveHDR.shadergraph", "Assets/Art/Shaders/SG_ParticleAdditiveHDR.shadergraph", typeof(UnityEngine.Shader), new [] {""}),
			new AddressableConfig(128, "Assets/Art/Materials/Particles/M_FireAndSmoke.mat", "Assets/Art/Materials/Particles/M_FireAndSmoke.mat", typeof(UnityEngine.Material), new [] {""}),
			new AddressableConfig(129, "Assets/Art/Materials/Particles/M_Beam.mat", "Assets/Art/Materials/Particles/M_Beam.mat", typeof(UnityEngine.Material), new [] {""}),
			new AddressableConfig(130, "Assets/Art/Textures/Particles/T_SmokeAtlas_6x6.png", "Assets/Art/Textures/Particles/T_SmokeAtlas_6x6.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(131, "Assets/Art/Textures/Particles/VignetteMask.png", "Assets/Art/Textures/Particles/VignetteMask.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(132, "Assets/Art/Shaders/SG_Silhouette.shadergraph", "Assets/Art/Shaders/SG_Silhouette.shadergraph", typeof(UnityEngine.Shader), new [] {""}),
			new AddressableConfig(133, "Assets/Art/Models/Items/Lost_Items.fbx", "Assets/Art/Models/Items/Lost_Items.fbx", typeof(UnityEngine.GameObject), new [] {""}),
			new AddressableConfig(134, "Assets/Art/VFXGraphs/SpawnOrb.vfx", "Assets/Art/VFXGraphs/SpawnOrb.vfx", typeof(UnityEngine.VFX.VisualEffectAsset), new [] {""}),
			new AddressableConfig(135, "Assets/Art/Materials/PM_Environment.physicMaterial", "Assets/Art/Materials/PM_Environment.physicMaterial", typeof(UnityEngine.PhysicMaterial), new [] {""}),
			new AddressableConfig(136, "Assets/Art/Models/Environment/Props/Barrels.fbx", "Assets/Art/Models/Environment/Props/Barrels.fbx", typeof(UnityEngine.GameObject), new [] {""}),
			new AddressableConfig(137, "Assets/Art/Models/Environment/Props/T_DomesticJunk_C.tga", "Assets/Art/Models/Environment/Props/T_DomesticJunk_C.tga", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(138, "Assets/Art/Animation/Humanoid/place.anim", "Assets/Art/Animation/Humanoid/place.anim", typeof(UnityEngine.AnimationClip), new [] {""}),
			new AddressableConfig(139, "Assets/Art/Animation/Humanoid/idle02.anim", "Assets/Art/Animation/Humanoid/idle02.anim", typeof(UnityEngine.AnimationClip), new [] {""}),
			new AddressableConfig(140, "Assets/Art/Animation/Humanoid/leap.anim", "Assets/Art/Animation/Humanoid/leap.anim", typeof(UnityEngine.AnimationClip), new [] {""}),
			new AddressableConfig(141, "Assets/Art/Animation/Humanoid/Inventory_Anims.fbx", "Assets/Art/Animation/Humanoid/Inventory_Anims.fbx", typeof(UnityEngine.GameObject), new [] {""}),
			new AddressableConfig(142, "Assets/Art/Animation/Humanoid/Humanoid_Anims.fbx", "Assets/Art/Animation/Humanoid/Humanoid_Anims.fbx", typeof(UnityEngine.GameObject), new [] {""}),
			new AddressableConfig(143, "Assets/Art/Animation/Humanoid/death.anim", "Assets/Art/Animation/Humanoid/death.anim", typeof(UnityEngine.AnimationClip), new [] {""}),
			new AddressableConfig(144, "Assets/Art/Models/Weapons/M_WeaponAtlas01.mat", "Assets/Art/Models/Weapons/M_WeaponAtlas01.mat", typeof(UnityEngine.Material), new [] {""}),
			new AddressableConfig(145, "Assets/Art/Models/Weapons/Rifle_AK.fbx", "Assets/Art/Models/Weapons/Rifle_AK.fbx", typeof(UnityEngine.GameObject), new [] {""}),
			new AddressableConfig(146, "Assets/Art/Models/Weapons/T_WeaponAtlas01_C.tga", "Assets/Art/Models/Weapons/T_WeaponAtlas01_C.tga", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(147, "Assets/Art/Fonts/DynamicDuo/DynamicDuo Heavy Italic SDF.asset", "Assets/Art/Fonts/DynamicDuo/DynamicDuo Heavy Italic SDF.asset", typeof(TMPro.TMP_FontAsset), new [] {""}),
			new AddressableConfig(148, "DynamicDuo Heavy Italic SDF Outline Plus Drop A", "Assets/Art/Fonts/DynamicDuo/DynamicDuo Heavy Italic SDF Outline Plus Drop A.mat", typeof(UnityEngine.Material), new [] {""}),
			new AddressableConfig(149, "Assets/Art/Textures/Ui/SharedUI/ShadowFade.png", "Assets/Art/Textures/Ui/SharedUI/ShadowFade.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(150, "Assets/Libs/TextMesh Pro/Fonts/LiberationSans.ttf", "Assets/Libs/TextMesh Pro/Fonts/LiberationSans.ttf", typeof(UnityEngine.Font), new [] {""}),
			new AddressableConfig(151, "Assets/Art/Animation/UI/Buttons/DefaultButtonSelectPress2.anim", "Assets/Art/Animation/UI/Buttons/DefaultButtonSelectPress2.anim", typeof(UnityEngine.AnimationClip), new [] {""}),
			new AddressableConfig(152, "Assets/Art/Fonts/DynamicDuo/DynamicDuo Heavy Italic SDF Outline Plus Drop B.mat", "Assets/Art/Fonts/DynamicDuo/DynamicDuo Heavy Italic SDF Outline Plus Drop B.mat", typeof(UnityEngine.Material), new [] {""}),
			new AddressableConfig(153, "Assets/Art/Textures/Ui/LootScreen/LootSelectBButton.png", "Assets/Art/Textures/Ui/LootScreen/LootSelectBButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(154, "Assets/Art/SpriteAtlas/MainMenuHud.spriteatlas", "Assets/Art/SpriteAtlas/MainMenuHud.spriteatlas", typeof(UnityEngine.U2D.SpriteAtlas), new [] {""}),
			new AddressableConfig(155, "Assets/Art/Textures/Ui/Home Screen/CrateIcon.png", "Assets/Art/Textures/Ui/Home Screen/CrateIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(156, "Assets/Art/Textures/Ui/Home Screen/IconHome.png", "Assets/Art/Textures/Ui/Home Screen/IconHome.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(157, "Assets/Art/Textures/Ui/LootScreen/WeaponNameBg.png", "Assets/Art/Textures/Ui/LootScreen/WeaponNameBg.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(158, "Assets/Art/Textures/Ui/EquipmentScreen/ItemCardEmpty.png", "Assets/Art/Textures/Ui/EquipmentScreen/ItemCardEmpty.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(159, "Assets/Art/Textures/Ui/LootScreen/EquipSlotEmpty.png", "Assets/Art/Textures/Ui/LootScreen/EquipSlotEmpty.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(160, "Assets/Art/Textures/Ui/TopBar/TopBarCell.png", "Assets/Art/Textures/Ui/TopBar/TopBarCell.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(161, "Assets/Art/Textures/Ui/LootScreen/EquipSlotSelect2x.png", "Assets/Art/Textures/Ui/LootScreen/EquipSlotSelect@2x.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(162, "Assets/Art/Textures/Ui/TopBar/TopBarCellEnd.png", "Assets/Art/Textures/Ui/TopBar/TopBarCellEnd.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(163, "Assets/Art/Textures/Ui/EquipmentScreen/SortArrows.png", "Assets/Art/Textures/Ui/EquipmentScreen/SortArrows.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(164, "Assets/Art/Textures/Ui/Home Screen/CharacterIcon.png", "Assets/Art/Textures/Ui/Home Screen/CharacterIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(165, "Assets/Art/Textures/Ui/Home Screen/AreaButtonB.png", "Assets/Art/Textures/Ui/Home Screen/AreaButtonB.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(166, "Assets/Art/Textures/Ui/TopBar/TopBarBase.png", "Assets/Art/Textures/Ui/TopBar/TopBarBase.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(167, "Assets/Art/Textures/Ui/Home Screen/TrophyBlank.png", "Assets/Art/Textures/Ui/Home Screen/TrophyBlank.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(168, "Assets/Art/Textures/Ui/MainMenuHUD/MainMenuSelected.png", "Assets/Art/Textures/Ui/MainMenuHUD/MainMenuSelected.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(169, "Assets/Art/Textures/Ui/LootScreen/BackButton.png", "Assets/Art/Textures/Ui/LootScreen/BackButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(170, "Assets/Art/Textures/Ui/Home Screen/MapButton.png", "Assets/Art/Textures/Ui/Home Screen/MapButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(171, "Assets/Art/Textures/Ui/EquipmentScreen/EquipmentFrame.png", "Assets/Art/Textures/Ui/EquipmentScreen/EquipmentFrame.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(172, "Assets/Art/Textures/Ui/EquipmentScreen/AimAutoIcon.png", "Assets/Art/Textures/Ui/EquipmentScreen/AimAutoIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(173, "Assets/Art/Textures/Ui/Home Screen/CraftIcon.png", "Assets/Art/Textures/Ui/Home Screen/CraftIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(174, "Assets/Art/Textures/Ui/Home Screen/RewardShape.png", "Assets/Art/Textures/Ui/Home Screen/RewardShape.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(175, "Assets/Art/Textures/Ui/LootScreen/EquipSlotEmpty2x.png", "Assets/Art/Textures/Ui/LootScreen/EquipSlotEmpty@2x.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(176, "Assets/Art/Textures/Ui/EquipmentScreen/ItemCardeRare.png", "Assets/Art/Textures/Ui/EquipmentScreen/ItemCardeRare.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(177, "Assets/Art/Textures/Ui/TopBar/TopBarEndReverse.png", "Assets/Art/Textures/Ui/TopBar/TopBarEndReverse.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(178, "Assets/Art/Textures/Ui/Home Screen/HomeButton.png", "Assets/Art/Textures/Ui/Home Screen/HomeButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(179, "Assets/Art/Textures/Ui/Buttons/BurgerButton_Blue.png", "Assets/Art/Textures/Ui/Buttons/BurgerButton_Blue.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(180, "Assets/Art/Textures/Ui/Home Screen/RewardsBase.png", "Assets/Art/Textures/Ui/Home Screen/RewardsBase.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(181, "Assets/Art/Textures/Ui/LootScreen/LootIconAmulet.png", "Assets/Art/Textures/Ui/LootScreen/LootIconAmulet.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(182, "Assets/Art/Textures/Ui/Home Screen/SettingsCog.png", "Assets/Art/Textures/Ui/Home Screen/SettingsCog.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(183, "Assets/Art/Textures/Ui/LootScreen/GunItemIcon.png", "Assets/Art/Textures/Ui/LootScreen/GunItemIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(184, "Assets/Art/Textures/Ui/LootScreen/SmearNewWhite.png", "Assets/Art/Textures/Ui/LootScreen/SmearNewWhite.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(185, "Assets/Art/Textures/Ui/LootScreen/LootIconHeadgear.png", "Assets/Art/Textures/Ui/LootScreen/LootIconHeadgear.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(186, "Assets/Art/Textures/Ui/TopBar/TopBarPlayerLevelBadge.png", "Assets/Art/Textures/Ui/TopBar/TopBarPlayerLevelBadge.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(187, "Assets/Art/Textures/Ui/EquipmentScreen/AimManualIcon.png", "Assets/Art/Textures/Ui/EquipmentScreen/AimManualIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(188, "Assets/Art/Textures/Ui/TopBar/TopBarCellFill.png", "Assets/Art/Textures/Ui/TopBar/TopBarCellFill.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(189, "Assets/Art/Textures/Ui/LootScreen/LightRays.png", "Assets/Art/Textures/Ui/LootScreen/LightRays.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(190, "Assets/Art/Textures/Ui/Home Screen/TrophyRoadHolder.png", "Assets/Art/Textures/Ui/Home Screen/TrophyRoadHolder.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(191, "Assets/Art/Textures/Ui/Buttons/CancelButton.png", "Assets/Art/Textures/Ui/Buttons/CancelButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(192, "Assets/Art/Textures/Ui/LootScreen/LootSelectAButton.png", "Assets/Art/Textures/Ui/LootScreen/LootSelectAButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(193, "Assets/Art/Textures/Ui/LootScreen/LootIconAll.png", "Assets/Art/Textures/Ui/LootScreen/LootIconAll.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(194, "Assets/Art/Textures/Ui/LootScreen/ShieldItemIcon.png", "Assets/Art/Textures/Ui/LootScreen/ShieldItemIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(195, "Assets/Art/Textures/Ui/Home Screen/NameHolder.png", "Assets/Art/Textures/Ui/Home Screen/NameHolder.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(196, "Assets/Art/Textures/Ui/LootScreen/LootIconShield.png", "Assets/Art/Textures/Ui/LootScreen/LootIconShield.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(197, "Assets/Art/Textures/Ui/Home Screen/ShopIcon.png", "Assets/Art/Textures/Ui/Home Screen/ShopIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(198, "Assets/Art/Textures/Ui/LootScreen/LootIconArmour.png", "Assets/Art/Textures/Ui/LootScreen/LootIconArmour.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(199, "Assets/Art/Textures/Ui/Home Screen/TrophyIcon.png", "Assets/Art/Textures/Ui/Home Screen/TrophyIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(200, "Assets/Art/Textures/Ui/Buttons/PopUp_Close.png", "Assets/Art/Textures/Ui/Buttons/PopUp_Close.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(201, "Assets/Art/Textures/Ui/Home Screen/AreaButtonA.png", "Assets/Art/Textures/Ui/Home Screen/AreaButtonA.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(202, "Assets/Art/Textures/Ui/EquipmentScreen/CardShine.png", "Assets/Art/Textures/Ui/EquipmentScreen/CardShine.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(203, "Assets/Art/Textures/Ui/Home Screen/TrophyRoadHolderNew.png", "Assets/Art/Textures/Ui/Home Screen/TrophyRoadHolderNew.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(204, "Assets/Art/Textures/Ui/LootScreen/LightRaysColor.png", "Assets/Art/Textures/Ui/LootScreen/LightRaysColor.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(205, "Assets/Art/Textures/Ui/LootScreen/FootwearItemIcon.png", "Assets/Art/Textures/Ui/LootScreen/FootwearItemIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(206, "Assets/Art/Textures/Ui/LootScreen/ChacterAvatarIcon.png", "Assets/Art/Textures/Ui/LootScreen/ChacterAvatarIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(207, "Assets/Art/Textures/Ui/Home Screen/RankBase.png", "Assets/Art/Textures/Ui/Home Screen/RankBase.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(208, "Assets/Art/Textures/Ui/EquipmentScreen/Group 28 2x.png", "Assets/Art/Textures/Ui/EquipmentScreen/Group 28@2x.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(209, "Assets/Art/Textures/Ui/EquipmentScreen/XP_Level_Icon.png", "Assets/Art/Textures/Ui/EquipmentScreen/XP_Level_Icon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(210, "Assets/Art/Textures/Ui/LootScreen/GearBag.png", "Assets/Art/Textures/Ui/LootScreen/GearBag.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(211, "Assets/Art/Textures/Ui/Home Screen/PlayButton.png", "Assets/Art/Textures/Ui/Home Screen/PlayButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(212, "Assets/Art/Textures/Ui/Buttons/UnavailableButton.png", "Assets/Art/Textures/Ui/Buttons/UnavailableButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(213, "Assets/Art/Textures/Ui/Home Screen/Settings.png", "Assets/Art/Textures/Ui/Home Screen/Settings.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(214, "Assets/Art/Textures/Ui/Buttons/ToggleOff.png", "Assets/Art/Textures/Ui/Buttons/ToggleOff.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(215, "Assets/Art/Textures/Ui/EquipmentScreen/MovieIconSmall.png", "Assets/Art/Textures/Ui/EquipmentScreen/MovieIconSmall.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(216, "Assets/Art/Textures/Ui/LootScreen/ArmourItemIcon.png", "Assets/Art/Textures/Ui/LootScreen/ArmourItemIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(217, "Assets/Art/Textures/Ui/TopBar/TrophyRoadButton.png", "Assets/Art/Textures/Ui/TopBar/TrophyRoadButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(218, "Assets/Art/Textures/Ui/Home Screen/SocialIcon.png", "Assets/Art/Textures/Ui/Home Screen/SocialIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(219, "Assets/Art/Textures/Ui/Buttons/DiscordButton.png", "Assets/Art/Textures/Ui/Buttons/DiscordButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(220, "Assets/Art/Textures/Ui/Home Screen/EnhanceIcon.png", "Assets/Art/Textures/Ui/Home Screen/EnhanceIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(221, "Assets/Art/Textures/Ui/LootScreen/BackHomeIcon.png", "Assets/Art/Textures/Ui/LootScreen/BackHomeIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(222, "Assets/Art/Textures/Ui/LootScreen/BackIcon.png", "Assets/Art/Textures/Ui/LootScreen/BackIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(223, "Assets/Art/Textures/Ui/EquipmentScreen/EquipmentFrame 1.png", "Assets/Art/Textures/Ui/EquipmentScreen/EquipmentFrame 1.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(224, "Assets/Art/Textures/Ui/Home Screen/FuseIcon.png", "Assets/Art/Textures/Ui/Home Screen/FuseIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(225, "Assets/Art/Textures/Ui/EquipmentScreen/EquipmentFrameA.png", "Assets/Art/Textures/Ui/EquipmentScreen/EquipmentFrameA.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(226, "Assets/Art/Textures/Ui/Buttons/GreenButton.png", "Assets/Art/Textures/Ui/Buttons/GreenButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(227, "Assets/Art/Textures/Ui/LootScreen/ChacterAvatarIcon2.png", "Assets/Art/Textures/Ui/LootScreen/ChacterAvatarIcon2.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(228, "Assets/Art/Textures/Ui/Notifications/NotificationUnique.png", "Assets/Art/Textures/Ui/Notifications/NotificationUnique.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(229, "Assets/Art/Textures/Ui/LootScreen/HeadgearItemIcon.png", "Assets/Art/Textures/Ui/LootScreen/HeadgearItemIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(230, "Assets/Art/Textures/Ui/Home Screen/RewardsSliderGraphic.png", "Assets/Art/Textures/Ui/Home Screen/RewardsSliderGraphic.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(231, "Assets/Art/Textures/Ui/Home Screen/SquadButton.png", "Assets/Art/Textures/Ui/Home Screen/SquadButton.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(232, "Assets/Art/Textures/Ui/LootScreen/ItemCardLootSlot2.png", "Assets/Art/Textures/Ui/LootScreen/ItemCardLootSlot2.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(233, "Assets/Art/Textures/Ui/Notifications/NotificationGroup.png", "Assets/Art/Textures/Ui/Notifications/NotificationGroup.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(234, "Assets/Art/Textures/Ui/EquipmentScreen/Weapon_AK.png", "Assets/Art/Textures/Ui/EquipmentScreen/Weapon_AK.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(235, "Assets/Art/Textures/Ui/Home Screen/HomeButtonFlipped.png", "Assets/Art/Textures/Ui/Home Screen/HomeButtonFlipped.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(236, "Assets/Art/Textures/Ui/LootScreen/LootIconSkills.png", "Assets/Art/Textures/Ui/LootScreen/LootIconSkills.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(237, "Assets/Art/Textures/Ui/EquipmentScreen/EquippedItem.png", "Assets/Art/Textures/Ui/EquipmentScreen/EquippedItem.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(238, "Assets/Art/Textures/Ui/LootScreen/SmearNewShadow.png", "Assets/Art/Textures/Ui/LootScreen/SmearNewShadow.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(239, "Assets/Art/Textures/Ui/TopBar/TopBarEnd.png", "Assets/Art/Textures/Ui/TopBar/TopBarEnd.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(240, "Assets/Art/Textures/Ui/EquipmentScreen/Group 28.png", "Assets/Art/Textures/Ui/EquipmentScreen/Group 28.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(241, "Assets/Art/Textures/Ui/LootScreen/Smear_Title_Black.png", "Assets/Art/Textures/Ui/LootScreen/Smear_Title_Black.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(242, "Assets/Art/Textures/Ui/EquipmentScreen/ItemDecal.png", "Assets/Art/Textures/Ui/EquipmentScreen/ItemDecal.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(243, "Assets/Art/Textures/Ui/Buttons/ToggleOn.png", "Assets/Art/Textures/Ui/Buttons/ToggleOn.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(244, "Assets/Art/Textures/Ui/LootScreen/LootIconWeapon.png", "Assets/Art/Textures/Ui/LootScreen/LootIconWeapon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(245, "Assets/Art/Textures/Ui/LootScreen/AmuletItemIcon.png", "Assets/Art/Textures/Ui/LootScreen/AmuletItemIcon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(246, "Assets/Art/Textures/Ui/TopBar/TopBarEnergy_Icon.png", "Assets/Art/Textures/Ui/TopBar/TopBarEnergy_Icon.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(247, "Assets/Art/Textures/Ui/SharedUI/DefaultBase.png", "Assets/Art/Textures/Ui/SharedUI/DefaultBase.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(248, "Assets/Art/Timelines/UI/Signals/Director Complete Signal.signal", "Assets/Art/Timelines/UI/Signals/Director Complete Signal.signal", typeof(UnityEngine.Timeline.SignalAsset), new [] {""}),
			new AddressableConfig(249, "Assets/Art/Animation/UI/GenericDialog/GenericDialog_Appear.anim", "Assets/Art/Animation/UI/GenericDialog/GenericDialog_Appear.anim", typeof(UnityEngine.AnimationClip), new [] {""}),
			new AddressableConfig(250, "Assets/Art/Animation/UI/GenericDialog/GenericDialog_Unpack.anim", "Assets/Art/Animation/UI/GenericDialog/GenericDialog_Unpack.anim", typeof(UnityEngine.AnimationClip), new [] {""}),
			new AddressableConfig(251, "Assets/Art/Textures/Ui/SharedUI/DefaultArrowUp.png", "Assets/Art/Textures/Ui/SharedUI/DefaultArrowUp.png", typeof(UnityEngine.Texture2D), new [] {""}),
			new AddressableConfig(252, "Assets/Art/Fonts/JockeyOne/JockeyOne-Regular SDF-InGame.asset", "Assets/Art/Fonts/JockeyOne/JockeyOne-Regular SDF-InGame.asset", typeof(TMPro.TMP_FontAsset), new [] {""}),
			new AddressableConfig(253, "Assets/Art/Materials/Particles/M_PickupSpot.mat", "Assets/Art/Materials/Particles/M_PickupSpot.mat", typeof(UnityEngine.Material), new [] {""}),
			new AddressableConfig(254, "Assets/Art/Models/Environment/Terrains/Arena_SkyBase01.fbx", "Assets/Art/Models/Environment/Terrains/Arena_SkyBase01.fbx", typeof(UnityEngine.GameObject), new [] {""}),
			new AddressableConfig(255, "Assets/Art/Models/Environment/BattleRoyalMaps/RoyaleMap01.fbx", "Assets/Art/Models/Environment/BattleRoyalMaps/RoyaleMap01.fbx", typeof(UnityEngine.GameObject), new [] {""}),
			new AddressableConfig(256, "Assets/AddressableResources/Fonts/LiberationSans SDF.asset", "Assets/AddressableResources/TMP Pro/Fonts/LiberationSans SDF.asset", typeof(TMPro.TMP_FontAsset), new [] {""}),
			new AddressableConfig(257, "Assets/AddressableResources/Fonts/LiberationSans SDF - Fallback.asset", "Assets/AddressableResources/TMP Pro/Fonts/LiberationSans SDF - Fallback.asset", typeof(TMPro.TMP_FontAsset), new [] {""}),
			new AddressableConfig(258, "Assets/AddressableResources/TMP Pro/Shaders/TMP_SDF.shader", "Assets/AddressableResources/TMP Pro/Shaders/TMP_SDF.shader", typeof(UnityEngine.Shader), new [] {""}),
			new AddressableConfig(259, "Assets/AddressableResources/TMP Pro/Shaders/TMP_SDF-Mobile.shader", "Assets/AddressableResources/TMP Pro/Shaders/TMP_SDF-Mobile.shader", typeof(UnityEngine.Shader), new [] {""})
		}.AsReadOnly();
	}
}
