parameters:
  - name: helmRepoPassword
    type: string
    default: ''
  - name: dockerImage
    type: string
    default: ''
  - name: autoDeployIfServer
    default: ''
    type: string
    
stages:
  - template: deploy-game-logic.yml
    parameters:
      dockerImage: ${{ parameters.dockerImage }}
      autoDeployIfServer: ${{ parameters.autoDeployIfServer }}
      environment: dev
      system: dev
      minReplicas: 1
      maxReplicas: 2
      cpu: 1
      memory: 2Gi
      ipwhitelist: 0.0.0.0/0
      helmRepoPassword: ${{ parameters.helmRepoPassword }}
      envVars: |
        --set autoscaling.enabled=true \
        --set autoscaling.minReplicas=1 \
        --set autoscaling.targetCPUUtilizationPercentage=190 \
        --set autoscaling.targetMemoryUtilizationPercentage=230 \
        --set env.API_KEY=$(DEV-COMMON-API-KEY) \
        --set env.API_URL="***REMOVED***" \
        --set env.APPLICATIONINSIGHTS_CONNECTION_STRING="$(DEV-COMMON-APP-INSIGHTS-CONNECTION-STRING)" \
        --set env.APPLICATION_ENVIRONMENT=dev \
        --set env.CONNECTION_STRING="$(DEV-BLOCKCHAIN-DB-CONNECTION-STRING-K8S)" \
        --set env.REMOTE_CONFIGURATION=false \
        --set env.DEV_MODE=TRUE \
        --set env.NFT_SYNC=true \
        --set env.PLAGUEDOCTOR_SYNC_ENABLED=true \
        --set env.GAMESGGGAMERS_SYNC_ENABLED=true \
        --set env.PLAYFAB_DEV_SECRET_KEY=$(DEV-COMMON-PLAYFAB-SECRET-KEY) \
        --set env.PLAYFAB_SECRET_KEY=$(DEV-COMMON-PLAYFAB-SECRET-KEY) \
        --set env.PLAYFAB_TITLE=***REMOVED*** \
        --set env.SqlConnectionString="$(DEV-BLOCKCHAIN-DB-CONNECTION-STRING-K8S)" \
        --set env.UNITY_CLOUD_AUTH_TOKEN="$(UNITY-CLOUD-JWT)" \
        --set env.UNITY_CLOUD_ENVIRONMENT_NAME="development" \
        --set env.UNITY_CLOUD_ENVIRONMENT_NAME="development" \
        --set env.UNITY_CLOUD_ENVIRONMENT_ID="***REMOVED***"