# Pipeline to release new containers on container apps

trigger: none
pr: none
# This pipeline doesn't use the current branch to deploy, it uses an image as parameter so it makes no sense to append the commit message to the run
appendCommitMessageToRunName: false
resources:
  repositories:
    - repository: templates
      type: git
      ref: main
      name: Infrastructure/core-templates

parameters:
  - name: imageOverwrite
    displayName: Image that will be deployed
  - name: serverEnvironment
    displayName: Select Target Server Environment
    type: string
    default: DEVELOPMENT_SERVER
    values:
      - DEVELOPMENT_SERVER
      - STAGE_SERVER
      - LIVE_TESTNET_SERVER
      - LIVE_SERVER
    

variables:
  # Variable called 'image_manual_override' is defined for optional per-run manual override.
  - group: Secrets
  - group: Non-secrets
    
pool: linux-k8s

stages:
  - ${{ if eq(parameters.serverEnvironment, 'LIVE_TESTNET_SERVER') }}:
    - template: deploy-game-logic-testnet.yml
      parameters:
        helmRepoPassword: $(HELM-REPO-PASSWORD)
        dockerImage: ${{ parameters.imageOverwrite }}

  - ${{ elseif eq(parameters.serverEnvironment, 'STAGE_SERVER') }}:
    - template: deploy-game-logic-staging.yml
      parameters:
        helmRepoPassword: $(HELM-REPO-PASSWORD)
        dockerImage: ${{ parameters.imageOverwrite }}
        
  - ${{ elseif eq(parameters.serverEnvironment, 'LIVE_SERVER') }}:
    - template: deploy-game-logic-prod.yml
      parameters:
        helmRepoPassword: $(HELM-REPO-PASSWORD)
        dockerImage: ${{ parameters.imageOverwrite }}
        
  - ${{ else }}:    
    - template: deploy-game-logic-dev.yml
      parameters:
        helmRepoPassword: $(HELM-REPO-PASSWORD)
        dockerImage: ${{ parameters.imageOverwrite }}



# autoscaling percentage values are bsed on request values, not limits.
# by default, we request 100 millicores. 190% of 100 millicores is 190 millicores.
