# Quantum Code Nuget Package build and release pipeline
# This pipeline is respsonsible for building the quantum code project and publishing the dlls to the nuget feed.
# PhotonDeterministic.dll
# quantum.core.dll
# quantum.code.dll

name: $(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - 'develop'
  paths:
    include:
    - Quantum
    - Assets/Libs/Photon/Quantum/Assemblies
    - pipeline-quantum-code.yml
pr: none

resources:
  repositories:
  - repository: self
  - repository: templates
    type: git
    ref: main
    name: Infrastructure/core-templates

variables:
- name: major
  value: "0"
- name: minor
  value: "0"
- name: version
  value: "$(major).$(minor).$(Build.BuildNumber)"

pool: vmss

stages:
- stage: Build
  displayName: Build and publish package
  jobs:
    - job: BuildPublish
      displayName: Build and publish
      steps:
      - checkout: self
        lfs: true
        submodules: true
      - template: pipelines/msbuild.yml@templates
        parameters:
          configuration: Debug
          version: $(version)
          csprojDirectory: Quantum/quantum_code/quantum.code
