# Android build and release pipeline
# This pipeline is respsonsible for building the Android APK, and uploading to Azure Storage.

name: $(Rev:r)

trigger: 
  batch: true
pr:
  branches:
    include:
    - master
    - develop
    - release/*
    - hotfix/*
parameters:
  - name: param_clean_library
    displayName: Clean Library Folder
    type: boolean
    default: false
variables:
- group: Secrets
- group: Non-secrets
pool: macos-tests-pool

stages:
- stage: EditorTests
  displayName: Editor Tests
  jobs:
    - job: EditorTests
      displayName: Run Editor Test Suite
      steps:
      - checkout: self
        lfs: true
        submodules: true  
        clean: false
      - bash: |
          echo "Removing library: ${{ parameters.param_clean_library }}"
          # remove temp files except library, we don't need to wait to recompile everything
          if [ "${{ parameters.param_clean_library }}" == "True" ]; then
            git clean -ffdx
          else
            git clean -ffdx --exclude="BlastRoyale/Library"
          fi
          git reset --hard HEAD
        # Run tests and copy dlls
      - template: unity-tests.yml
          
      # Game logic build
      - script: dotnet build
        workingDirectory: Backend
        displayName: 'Dotnet Build'
  
      - script: dotnet test TestUnit/TestUnit.csproj
        workingDirectory: Backend
        displayName: 'Dotnet Test'
