parameters:
  - name: helmRepoPassword
    type: string
    default: ''
  - name: dockerImage
    type: string
    default: ''
  - name: autoDeployIfServer
    default: ''
    type: string

stages:
  - template: deploy-game-logic.yml
    parameters:
      autoDeployIfServer: ${{ parameters.autoDeployIfServer }}
      dockerImage: ${{ parameters.dockerImage }}
      helmRepoPassword: ${{ parameters.helmRepoPassword }}     
      environment: staging
      system: staging
      minReplicas: 1
      maxReplicas: 2
      cpu: 1
      memory: 2Gi
      ipwhitelist: 0.0.0.0/0
      envVars: |
        --set autoscaling.enabled=true \
        --set autoscaling.minReplicas=1 \
        --set autoscaling.targetCPUUtilizationPercentage=190 \
        --set autoscaling.targetMemoryUtilizationPercentage=230 \

        --set env.API_KEY=$(STAGING-COMMON-API-KEY) \
        --set env.API_URL="https://staging-hub-blockchain-service.blastroyale.com" \
        --set env.APPLICATIONINSIGHTS_CONNECTION_STRING="$(STAGING-COMMON-APP-INSIGHTS-CONNECTION-STRING)" \
        --set env.APPLICATION_ENVIRONMENT=staging \
        --set env.REMOTE_CONFIGURATION=true \
        --set env.CONNECTION_STRING="$(STAGING-BLOCKCHAIN-DB-CONNECTION-STRING-K8S)" \
        --set env.DEV_MODE=false \
        --set env.NFT_SYNC=true \
        --set env.PLAYFAB_DEV_SECRET_KEY=$(STAGING-COMMON-PLAYFAB-SECRET-KEY) \
        --set env.PLAYFAB_SECRET_KEY=$(STAGING-COMMON-PLAYFAB-SECRET-KEY) \
        --set env.PLAYFAB_TITLE=***REMOVED*** \
        --set env.SqlConnectionString="$(STAGING-BLOCKCHAIN-DB-CONNECTION-STRING-K8S)"