using static FirstLight.Editor.Ids.Ids.GroupSource;

namespace FirstLight.Editor.Ids
{
	/// <summary>
	/// Used for generation, NEVER USE THIS FOR REFERENCE
	/// </summary>
	internal class Ids
	{
		/// <summary>
		/// Keep the same ids
		/// </summary>
		internal enum GroupSource : int
		{
			GameDesign = 0,
			Currency = 1,
			ResourcePool = 6,
			Resource = 5,
			Map = 8,
			Helmet = 13,
			Equipment = 12,
			Gear = 24,
			Simple = 25,
			Weapon = 11,
			Melee = 20,
			Deprecated = 34,
			Amulet = 16,
			Armor = 17,
			Shield = 15,
			Collection = 14,
			Assassin = 31,
			Corpo = 32,
			BotItem = 4,
			Punk = 30,
			Superstar = 29,
			Consumable = 19,
			Collectable = 27,
			Ammo = 7,
			Chest = 2,
			Special = 21,
			Destructible = 26,
			DummyCharacter = 3,
			Platform = 37,
			Core = 22,
			IAP = 23,
			GenericCollectionItem = 39,
			NOOBRareTokens = 40,
			CryptoCurrency = 41,


			#region CollectionGroup

			MeleeSkin = 38,
			PlayerSkin = 18,
			Glider = 28,
			DeathMarker = 10,
			ProfilePicture = 9,
			Footprint = 33,

			#endregion
		}

		internal static GameIdHolder GameIds = new ()
		{
			{"Random", 0, GameDesign},
			{"Any", 126, GameDesign },
			
			{"RealMoney", 125, Currency},
			{"COIN", 61, Currency},
			{"BlastBuck", 105, Currency},
			{"BLST", 14, Currency},
			{"Fragments", 112, Currency, Deprecated},
			{"NOOB", 209, Currency, CryptoCurrency},
			{"NOOBGolden", 249, Collectable, NOOBRareTokens},
			{"NOOBRainbow", 250, Collectable, NOOBRareTokens},
			{"CS", 12, Currency, ResourcePool},
			{"XP", 3, Resource},
			{"Trophies", 22, Resource},
			{"BPP", 26, Resource, ResourcePool},
			{"PartnerANCIENT8", 900, Currency, CryptoCurrency},
			{"PartnerAPECOIN", 901, Currency, CryptoCurrency},
			{"PartnerBEAM", 902, Currency, CryptoCurrency},
			{"PartnerBLOCKLORDS", 903, Currency, CryptoCurrency},
			{"PartnerBLOODLOOP", 904, Currency, CryptoCurrency},
			{"PartnerCROSSTHEAGES", 905, Currency, CryptoCurrency},
			{"PartnerFARCANA", 906, Currency, CryptoCurrency},
			{"PartnerGAM3SGG", 907, Currency, CryptoCurrency},
			{"PartnerIMMUTABLE", 908, Currency, CryptoCurrency},
			{"PartnerMOCAVERSE", 909, Currency, CryptoCurrency},
			{"PartnerNYANHEROES", 910, Currency, CryptoCurrency},
			{"PartnerPIRATENATION", 911, Currency, CryptoCurrency},
			{"PartnerPIXELMON", 912, Currency, CryptoCurrency},
			{"PartnerPLANETMOJO", 913, Currency, CryptoCurrency},
			{"PartnerSEEDIFY", 914, Currency, CryptoCurrency},
			{"PartnerWILDERWORLD", 915, Currency, CryptoCurrency},
			{"PartnerXBORG", 916, Currency, CryptoCurrency},
			{"PartnerBREED", 917, Currency, CryptoCurrency},
			{"PartnerMEME", 918, Currency, CryptoCurrency},
			{"PartnerYGG", 919, Currency, CryptoCurrency},
			{"FestiveSNOWFLAKE", 271, Currency, CryptoCurrency},
			{"EventTicket", 272, Currency, CryptoCurrency},
			{"FloodCity", 137, Map, Deprecated},
			{"MainDeck", 143, Map},
			{"FtueDeck", 5, Map},
			{"SmallWilderness", 144, Map},
			{"FloodCitySimple", 7, Map},
			{"BlimpDeck", 8, Map},
			{"BRGenesis", 9, Map},
			{"MapTestScene", 63, Map},
			{"TestScene", 11, Map},
			{"NewBRMap", 65, Map},
			{"FtueMiniMap", 133, Map},
			{"District", 108, Map},
			{"TestAssetsMap", 1009, Map},
			{"BattlelandsMap", 113, Map},
			{"IslandsMap", 114, Map},
			{"MazeMayhem", 115, Map},
			{"Cemetery", 197, Map},
			{"Fortress", 198, Map},
			{"IslandOne", 200, Map},
			{"MausHelmet", 24, Helmet, Equipment, Gear, Simple, Deprecated},
			{"SoldierHelmet", 49, Helmet, Equipment, Gear, Deprecated},
			{"RiotHelmet", 50, Helmet, Equipment, Gear, Deprecated},
			{"WarriorHelmet", 51, Helmet, Equipment, Gear, Deprecated},
			{"RoadHelmet", 23, Helmet, Equipment, Gear, Simple, Deprecated},
			{"FootballHelmet", 30, Helmet, Equipment, Gear, Deprecated},
			{"BaseballHelmet", 32, Helmet, Equipment, Gear, Deprecated},
			{"HockeyHelmet", 33, Helmet, Equipment, Gear, Deprecated},
			{"Hammer", 31, Weapon, Equipment, Melee},
			{"ApoCrossbow", 60, Weapon, Equipment, Deprecated},
			{"ApoShotgun", 71, Weapon, Equipment, Deprecated},
			{"ApoSMG", 78, Weapon, Equipment, Simple, Deprecated},
			{"ApoRifle", 79, Weapon, Equipment, Deprecated},
			{"ApoSniper", 84, Weapon, Equipment, Deprecated},
			{"ApoRPG", 86, Weapon, Equipment, Deprecated},
			{"ApoMinigun", 87, Weapon, Equipment},
			{"ModPistol", 88, Weapon, Equipment, Simple},
			{"ModShotgun", 90, Weapon, Equipment},
			{"ModMachineGun", 91, Weapon, Equipment},
			{"ModRifle", 92, Weapon, Equipment},
			{"ModSniper", 93, Weapon, Equipment},
			{"ModLauncher", 94, Weapon, Equipment},
			{"ModHeavyMachineGun", 95, Weapon, Equipment, Deprecated},
			{"SciPistol", 96, Weapon, Equipment, Deprecated},
			{"SciBlaster", 97, Weapon, Equipment, Deprecated},
			{"SciNeedleGun", 98, Weapon, Equipment, Deprecated},
			{"SciRifle", 99, Weapon, Equipment, Deprecated},
			{"SciSniper", 100, Weapon, Equipment, Deprecated},
			{"SciCannon", 101, Weapon, Equipment, Deprecated},
			{"SciMelter", 103, Weapon, Equipment, Deprecated},
			{"GunSniperHeavy", 269, Weapon, Equipment},
			{"GunARBurst", 270, Weapon, Equipment},
			{"MouseAmulet", 38, Amulet, Equipment, Gear, Simple, Deprecated},
			{"RiotAmulet", 39, Amulet, Equipment, Gear, Deprecated},
			{"SoldierAmulet", 40, Amulet, Equipment, Gear, Deprecated},
			{"WarriorAmulet", 41, Amulet, Equipment, Gear, Deprecated},
			{"TikTokAmulet", 28, Amulet, Equipment, Gear, Simple, Deprecated},
			{"MouseArmor", 42, Armor, Equipment, Gear, Simple, Deprecated},
			{"RiotArmor", 43, Armor, Equipment, Gear, Deprecated},
			{"SoldierArmor", 44, Armor, Equipment, Gear, Deprecated},
			{"WarriorArmor", 45, Armor, Equipment, Gear, Deprecated},
			{"RoadSignArmour", 29, Armor, Equipment, Gear, Simple, Deprecated},
			{"BaseballArmor", 34, Armor, Equipment, Gear, Deprecated},
			{"FootballArmor", 35, Armor, Equipment, Gear, Deprecated},
			{"MouseShield", 52, Shield, Equipment, Gear, Simple, Deprecated},
			{"SoldierShield", 53, Shield, Equipment, Gear, Deprecated},
			{"WarriorShield", 54, Shield, Equipment, Gear, Deprecated},
			{"RiotShield", 27, Shield, Equipment, Gear, Deprecated},
			{"RoadShield", 36, Shield, Equipment, Gear, Simple, Deprecated},
			{"Rage", 64},
			{"Health", 4, Consumable, Collectable},
			{"AmmoSmall", 127, Consumable, Collectable, Ammo},
			{"AmmoLarge", 128},
			{"ShieldSmall", 20, Consumable, Collectable},
			{"ShieldLarge", 21},
			{"ShieldCapacitySmall", 17},
			{"ShieldCapacityLarge", 18},
			{"EnergyCubeSmall", 106},
			{"EnergyCubeLarge", 107},
			{"ChestCommon", 13},
			{"ChestUncommon", 1},
			{"ChestRare", 16},
			{"ChestEpic", 2},
			{"ChestConsumable", 131, Chest, Collectable},
			{"ChestEquipment", 130, Chest, Collectable},
			{"ChestEquipmentTutorial", 132, Chest, Collectable},
			{"ChestWeapon", 134, Chest, Collectable},
			{"ChestLegendary", 19, Chest, Collectable},
			{"ChestVitality", 220, Chest, Collectable},
			{"ChestAmmo", 221, Chest, Collectable},
			{"SpecialAimingAirstrike", 10, Special},
			{"SpecialAimingStunGrenade", 85, Special, Collectable},
			{"SpecialShieldSelf", 89, Special, Collectable},
			{"SpecialSkyLaserBeam", 110, Special, Collectable},
			{"SpecialShieldedCharge", 119, Special, Collectable},
			{"SpecialAimingGrenade", 102, Special, Collectable},
			{"SpecialDefaultDash", 141, Special, Collectable},
			{"SpecialRadar", 62, Special, Collectable},
			{"SpecialLandmine", 666, Special, Collectable},
			{"TutorialGrenade", 70, Special},
			{"Barrel", 109, Destructible},
			{"Barrier", 72, Destructible},
			{"SkipTutorial", 195, Destructible},
			{"DummyCharacter", 6, DummyCharacter},
			{"WeaponPlatformSpawner", 138, Platform},
			{"ConsumablePlatformSpawner", 140, Platform},
			{"CoreCommon", 15, Core, Deprecated},
			{"CoreUncommon", 46, Core, Deprecated},
			{"CoreRare", 47, Core, IAP, Chest, Deprecated},
			{"CoreEpic", 48, Core, IAP, Chest, Deprecated},
			{"CoreLegendary", 59, Core, IAP, Chest, Deprecated},

			#region Collections

			#region Player Skins

			{"Male01Avatar", 55, Deprecated },
			{"Male02Avatar", 56, Deprecated},
			{"Female01Avatar", 57, Deprecated},
			{"Female02Avatar", 58, Deprecated},
			{"MaleAssassin", 68, PlayerSkin, BotItem, Assassin, Collection},
			{"MaleCorpos", 69, PlayerSkin, Corpo, Collection},
			{"MalePunk", 77, PlayerSkin, Punk, Collection},
			{"MaleSuperstar", 80, PlayerSkin, Superstar, Collection},
			{"FemaleAssassin", 81, PlayerSkin, BotItem, Assassin, Collection},
			{"FemaleCorpos", 82, PlayerSkin, Corpo, Collection},
			{"FemalePunk", 83, PlayerSkin, Punk, Collection},
			{"FemaleSuperstar", 104, PlayerSkin, Superstar, Collection},
			{"TestSkin", 122},
			{"PlayerSkinDragonBoxer", 148}, // placeholder ID for the future skin
			{"PlayerSkinTieGuy", 147}, // placeholder ID for the future skin
			{"PlayerSkinFitnessChick", 146}, // placeholder ID for the future skin
			{"PlayerSkinSkellyQueen", 145}, // placeholder ID for the future skin
			{"PlayerSkinXmasSuperstar", 149, PlayerSkin, Collection},
			{"PlayerSkinJodie", 135}, // placeholder ID for the future skin
			{"PlayerSkinMontyVonCue", 136}, // placeholder ID for the future skin
			{"PlayerSkinBoudicca", 139}, // placeholder ID for the future skin
			{"PlayerSkinCupid", 142, PlayerSkin, Collection},
			{"PlayerSkinPanda", 400, PlayerSkin, Collection},
			{"PlayerSkinDragon", 402}, // placeholder ID for the future skin
			{"PlayerSkinSnowboarder", 403, PlayerSkin, Collection},
			{"PlayerSkinDunePaul", 404, PlayerSkin, Collection},
			{"PlayerSkinViking", 405, PlayerSkin, Collection},
			{"PlayerSkinLeprechaun", 401, PlayerSkin, Collection},
			{"PlayerSkinEGirl", 196, PlayerSkin, Collection, BotItem},
			{"PlayerSkinPoliceFemale", 199, PlayerSkin, Collection},
			{"PlayerSkinNinja", 201, PlayerSkin, Collection},
			{"PlayerSkinBrandFemale", 202, PlayerSkin, Collection, BotItem},
			{"PlayerSkinBrandMale", 203, PlayerSkin, Collection, BotItem},
			{"PlayerSkinGearedApe", 204, PlayerSkin, Collection},
			{"PlayerSkinPlagueDoctor", 205, PlayerSkin, Collection},
			{"PlayerSkinBurger", 210, PlayerSkin, Collection},
			{"PlayerSkinFootballGuy", 211, PlayerSkin, Collection},
			{"PlayerSkinLincoln", 212, PlayerSkin, Collection},
			{"PlayerSkinLion", 213, PlayerSkin, Collection},
			{"PlayerSkinSatoshi", 214, PlayerSkin, Collection},
			{"PlayerSkinSheriff", 215, PlayerSkin, Collection},
			{"PlayerSkinSoldier", 216, PlayerSkin, Collection, BotItem},
			{"PlayerSkinSwimmer", 217, PlayerSkin, Collection},
			{"PlayerSkinThief", 218, PlayerSkin, Collection},
			{"PlayerSkinVR", 219, PlayerSkin, Collection},
			{"PlayerSkinWitch", 222, PlayerSkin, Collection},
			{"PlayerSkinHazmat", 230, PlayerSkin, Collection},
			{"PlayerSkinAura", 231, PlayerSkin, Collection},
			{"PlayerSkinMidas", 234, PlayerSkin, Collection},
			{"PlayerSkinNFL", 237, PlayerSkin, Collection},
			{"PlayerSkinPilot", 241, PlayerSkin, Collection},
			{"PlayerSkinSkeleton", 242, PlayerSkin, Collection},
            {"PlayerSkinFemale01", 245, PlayerSkin, Collection},
            {"PlayerSkinFemale02", 246, PlayerSkin, Collection},
            {"PlayerSkinMale01", 247, PlayerSkin, Collection},
            {"PlayerSkinMale02", 248, PlayerSkin, Collection},
			{"PlayerSkinGamer", 251, PlayerSkin, Collection},
			{"PlayerSkinFarmer", 252, PlayerSkin, Collection},
			{"PlayerSkinFirefighter", 253, PlayerSkin, Collection},
			{"PlayerSkinGingerbread", 254, PlayerSkin, Collection},
			{"PlayerSkinIceking", 255, PlayerSkin, Collection},
			{"PlayerSkinMechapilot", 256, PlayerSkin, Collection},
			{"PlayerSkinPirateCaptain", 257, PlayerSkin, Collection},
			{"PlayerSkinRenny", 258, PlayerSkin, Collection},
			{"PlayerSkinRobot", 259, PlayerSkin, Collection},
			{"PlayerSkinVikingfemale", 260, PlayerSkin, Collection},
			{"PlayerSkinAlien", 273, PlayerSkin, Collection},
			{"PlayerSkinBrazillianfestival", 274, PlayerSkin, Collection},
			{"PlayerSkinChinesedragon", 275, PlayerSkin, Collection},
			{"PlayerSkinFieldmedic", 276, PlayerSkin, Collection},
			{"PlayerSkinPolarexplorer", 277, PlayerSkin, Collection},
			{"PlayerSkinPostapocalypticassassin", 278, PlayerSkin, Collection},
			{"PlayerSkinStreetrunner", 279, PlayerSkin, Collection},
			{"PlayerSkinValkyrie", 280, PlayerSkin, Collection},
			{"PlayerSkinYeti", 281, PlayerSkin, Collection},
			// SKINS GENERATION TOKEN KEEP THIS HERE

			#endregion Player skins

			#region Gliders

			{"Divinci", 66, Glider, BotItem, Collection},
			{"Falcon", 67, Glider, BotItem, Collection},
			{"Rocket", 73, Glider, BotItem, Collection},
			{"Turbine", 74, Glider, BotItem, Collection},

			#endregion

			#region Deathmarkers

			{"Tombstone", 37, DeathMarker, BotItem, Collection},
			{"Demon", 25, DeathMarker, BotItem, Collection},
			{"Superstar", 75, DeathMarker, BotItem, Collection},
			{"Unicorn", 76, DeathMarker, BotItem, Collection},
			{"FlagBanana", 273, DeathMarker, BotItem, Collection},
			{"FlagFire", 274, DeathMarker, BotItem, Collection},
			{"FlagGG",  275, DeathMarker, BotItem, Collection},
			{"FlagLaughing", 276, DeathMarker, BotItem, Collection},
			{"FlagNoob", 277, DeathMarker, BotItem, Collection},
			{"FlagNumberOne", 278, DeathMarker, BotItem, Collection},
			{"FlagPooEmoji", 279, DeathMarker, BotItem, Collection},
			{"FlagRoyalCrown", 280, DeathMarker, BotItem, Collection},
			{"FlagSalt", 281, DeathMarker, BotItem, Collection},
			#endregion

			#region MeleeSkins

			{"MeleeSkinDefault", 300, MeleeSkin, Collection, BotItem},
			{"MeleeSkinSausage", 301, MeleeSkin, Collection},
			{"MeleeSkinCactus", 302, MeleeSkin, Collection},
			{"MeleeSkinAtomSlicer", 303, MeleeSkin, Collection},
			{"MeleeSkinDaggerOfDestiny", 304, MeleeSkin, Collection, BotItem},
			{"MeleeSkinElectricSolo", 305, MeleeSkin, Collection, BotItem},
			{"MeleeSkinGigaMelee", 306, MeleeSkin, Collection},
			{"MeleeSkinHatchet", 307, MeleeSkin, Collection},
			{"MeleeSkinMicDrop", 308, MeleeSkin, Collection, BotItem},
			{"MeleeSkinMightySledge", 309, MeleeSkin, Collection},
			{"MeleeSkinOutOfThePark", 310, MeleeSkin, Collection, BotItem},
			{"MeleeSkinPowerPan", 311, MeleeSkin, Collection, BotItem},
			{"MeleeSkinPutter", 312, MeleeSkin, Collection},
			{"MeleeSkinSirQuacks", 313, MeleeSkin, Collection},
			{"MeleeSkinThunderAxe", 314, MeleeSkin, Collection, BotItem},
			{"MeleeSkinToyMelee", 315, MeleeSkin, Collection, BotItem},
			{"MeleeSkinTvTakedown", 316, MeleeSkin, Collection, BotItem},
			{"MeleeSkinWheelOfPain", 317, MeleeSkin, Collection, BotItem},
			{"MeleeSkinWrench", 318, MeleeSkin, Collection},
			{"MeleeSkinYouGotMail", 319, MeleeSkin, Collection, BotItem},
			{"MeleeSkinXmas2023", 320, MeleeSkin, Collection, BotItem},
			{"MeleeSkinBaton", 129, MeleeSkin, Collection},
			{"MeleeSkinKatana", 206, MeleeSkin, Collection},
			{"MeleeSkinKeyboard", 207, MeleeSkin, Collection},
			{"MeleeSkinMagicalShillelagh", 208, MeleeSkin, Collection},
			{"MeleeSkinCrowbar", 223, MeleeSkin, Collection},
			{"MeleeSkinAxe", 224, MeleeSkin, Collection},
			{"MeleeSkinKnife", 225, MeleeSkin, Collection},
			{"MeleeSkinOar", 226, MeleeSkin, Collection},
			{"MeleeSkinSpatula", 227, MeleeSkin, Collection},
			{"MeleeSkinTrophy", 228, MeleeSkin, Collection},
			{"MeleeSkinWalkingStick", 229, MeleeSkin, Collection},
			{"MeleeSkinBroccoli", 232, MeleeSkin, Collection},
			{"MeleeSkinBone", 233, MeleeSkin, Collection},
			{"MeleeSkinBroom", 235, MeleeSkin, Collection},
			{"MeleeSkinLightsaber", 238, MeleeSkin, Collection},
			{"MeleeSkinScythe", 239, MeleeSkin, Collection},
			{"MeleeSkinSickle", 240, MeleeSkin, Collection},
			{"MeleeSkinPickaxe", 243, MeleeSkin, Collection},
			{"MeleeSkinLollipop", 244, MeleeSkin, Collection},
			{"MeleeSkinDoctorStaff", 236, MeleeSkin, Collection},
			{"MeleeSkinBaguette", 261, MeleeSkin, Collection},
			{"MeleeSkinBananaHammer", 262, MeleeSkin, Collection},
			{"MeleeSkinFirefighterAxe", 263, MeleeSkin, Collection},
			{"MeleeSkinNoobHammer", 264, MeleeSkin, Collection},
			{"MeleeSkinRollingPin", 265, MeleeSkin, Collection},
			{"MeleeSkinRoyalStaff", 266, MeleeSkin, Collection},
			{"MeleeSkinStopSign", 267, MeleeSkin, Collection},
			{"MeleeSkinVikingAxe", 268, MeleeSkin, Collection},
			{"MeleeSkinBigsyringe", 321, MeleeSkin, Collection},
			{"MeleeSkinValkyriesword", 322, MeleeSkin, Collection},
			{"MeleeSkinIceсlub", 333, MeleeSkin, Collection},
			{"MeleeSkinHotdog", 334, MeleeSkin, Collection},
			{"MeleeSkinFish", 335, MeleeSkin, Collection},
			{"MeleeSkinFestivefeather", 336, MeleeSkin, Collection},
			{"MeleeSkinChinesefan", 337, MeleeSkin, Collection},
			{"MeleeSkinChemosword", 338, MeleeSkin, Collection},
			{"MeleeSkinCarкepairрammer", 339, MeleeSkin, Collection},
			// WEAPON GENERATION TOKEN KEEP THIS HERE
			
			#endregion

			#region ProfilePictures

			{"Avatar1", 116, ProfilePicture, Collection},
			{"Avatar2", 117, ProfilePicture, Collection},
			{"Avatar3", 118, ProfilePicture, Collection},
			{"Avatar4", 120, ProfilePicture, Collection},
			{"Avatar5", 121, ProfilePicture, Collection},
			{"AvatarRemote", 123, ProfilePicture, Collection, GenericCollectionItem},
			{"AvatarNFTCollection", 124, ProfilePicture, Collection, GenericCollectionItem},
			{"AvatarAssasinmask", 150, ProfilePicture, Collection},
			{"AvatarBlastcatads", 151, ProfilePicture, Collection},
			{"AvatarBurgerads", 152, ProfilePicture, Collection},
			{"AvatarCatcupads", 153, ProfilePicture, Collection},
			{"AvatarCorpoads", 154, ProfilePicture, Collection},
			{"AvatarCorpocrossads", 155, ProfilePicture, Collection},
			{"AvatarCorpomask", 156, ProfilePicture, Collection},
			{"AvatarEyesads", 157, ProfilePicture, Collection},
			{"AvatarFemaleassasinwantedads", 158, ProfilePicture, Collection},
			{"AvatarFemaleassassinconcept", 159, ProfilePicture, Collection},
			{"AvatarFemaleassassinwhatsticker", 160, ProfilePicture, Collection},
			{"AvatarFemalecorpo", 161, ProfilePicture, Collection},
			{"AvatarFemalecorpoconcept", 162, ProfilePicture, Collection},
			{"AvatarFemalecorpophonesticker", 163, ProfilePicture, Collection},
			{"AvatarFemalecorposticker", 164, ProfilePicture, Collection},
			{"AvatarFemalehost", 165, ProfilePicture, Collection},
			{"AvatarFemalepunk", 166, ProfilePicture, Collection},
			{"AvatarFemalepunkconcept", 167, ProfilePicture, Collection},
			{"AvatarFemalepunkfunsticker", 168, ProfilePicture, Collection},
			{"AvatarFemalepunkgraffiti", 169, ProfilePicture, Collection},
			{"AvatarFemalesuperstarads", 170, ProfilePicture, Collection},
			{"AvatarFemalesuperstarconcept", 171, ProfilePicture, Collection},
			{"AvatarFemalesuperstardisguststicker", 172, ProfilePicture, Collection},
			{"AvatarFemalesupperstar", 173, ProfilePicture, Collection},
			{"AvatarMaleassasin", 174, ProfilePicture, Collection},
			{"AvatarMaleassasinconcept", 175, ProfilePicture, Collection},
			{"AvatarMaleassasinexcitedsticker", 176, ProfilePicture, Collection},
			{"AvatarMaleassasinwantedads", 177, ProfilePicture, Collection},
			{"AvatarMalecorpoangryads", 178, ProfilePicture, Collection},
			{"AvatarMalecorpoconcept", 179, ProfilePicture, Collection},
			{"AvatarMalecorposcaredsticker", 180, ProfilePicture, Collection},
			{"AvatarMalehost", 181, ProfilePicture, Collection},
			{"AvatarMalepunk", 182, ProfilePicture, Collection},
			{"AvatarMalepunkads", 183, ProfilePicture, Collection},
			{"AvatarMalepunkconcept", 184, ProfilePicture, Collection},
			{"AvatarMalepunkgraffiti", 185, ProfilePicture, Collection},
			{"AvatarMalepunkhahasticker", 186, ProfilePicture, Collection},
			{"AvatarMalesuperstarads", 187, ProfilePicture, Collection},
			{"AvatarMalesuperstarconcept", 188, ProfilePicture, Collection},
			{"AvatarMalesuperstarstopsticker", 189, ProfilePicture, Collection},
			{"AvatarMusic", 190, ProfilePicture, Collection},
			{"AvatarPunklogoads", 191, ProfilePicture, Collection},
			{"AvatarRocketads", 192, ProfilePicture, Collection},
			{"AvatarSuperstarloveads", 193, ProfilePicture, Collection},
			{"AvatarUnicornssticker", 194, ProfilePicture, Collection},
			{"AvatarBrandfemale", 500, ProfilePicture, Collection},
			{"AvatarBrandmale", 501, ProfilePicture, Collection},
			{"AvatarEgirl", 502, ProfilePicture, Collection},
			{"AvatarGearedape", 503, ProfilePicture, Collection},
			{"AvatarLeprechaun", 504, ProfilePicture, Collection},
			{"AvatarNinja", 505, ProfilePicture, Collection},
			{"AvatarNinjaalternative", 506, ProfilePicture, Collection},
			{"AvatarPolicefemale", 507, ProfilePicture, Collection},
			{"AvatarPlaguedoctormystery", 508, ProfilePicture, Collection},
			{"AvatarBurger", 509, ProfilePicture, Collection},
			{"AvatarFootballguy", 510, ProfilePicture, Collection},
			{"AvatarLion", 511, ProfilePicture, Collection},
			{"AvatarLion2", 512, ProfilePicture, Collection},
			{"AvatarSatoshi", 513, ProfilePicture, Collection},
			{"AvatarSheriff", 514, ProfilePicture, Collection},
			{"AvatarSoldier", 515, ProfilePicture, Collection},
			{"AvatarSwimmer", 516, ProfilePicture, Collection},
			{"AvatarThief", 517, ProfilePicture, Collection},
			{"AvatarVr", 518, ProfilePicture, Collection},
			{"AvatarBall", 519, ProfilePicture, Collection},
			{"AvatarLincoln", 520, ProfilePicture, Collection},
			{"AvatarMidasfull", 521, ProfilePicture, Collection},
			{"AvatarHazmatfull", 522, ProfilePicture, Collection},
			{"AvatarSkeletonfull", 523, ProfilePicture, Collection},
			{"AvatarWitchhat", 524, ProfilePicture, Collection},
			{"AvatarPumpkin", 525, ProfilePicture, Collection},
			{"AvatarAuraarmed", 526, ProfilePicture, Collection},
			{"AvatarNflarmed", 527, ProfilePicture, Collection},
			{"AvatarPilotarmed", 528, ProfilePicture, Collection},
			{"AvatarWitch", 529, ProfilePicture, Collection},
			{"AvatarIceking", 530, ProfilePicture, Collection},
			{"AvatarBanana", 531, ProfilePicture, Collection},
			{"AvatarFarmer", 532, ProfilePicture, Collection},
			{"AvatarFirefighter", 533, ProfilePicture, Collection},
			{"AvatarGingerbread", 534, ProfilePicture, Collection},
			{"AvatarMechapilot", 535, ProfilePicture, Collection},
			{"AvatarPirate", 536, ProfilePicture, Collection},
			{"AvatarRennyBest", 537, ProfilePicture, Collection},
			{"AvatarRennyBanana", 538, ProfilePicture, Collection},
			{"AvatarRobot", 539, ProfilePicture, Collection},
			{"AvatarVikingfemale", 540, ProfilePicture, Collection},

			#endregion

			#region Footprint

			{"FootprintDot", 111, Footprint, BotItem},

			#endregion

			#endregion
		};
	}
}